# MC Dropout Bayesian Neural Network Pipeline

This notebook continues after completed Steps 1-3:

1. Matrix completion artifacts from `artifacts/matrix/`
2. Transformer product embedding artifacts from `artifacts/transformer/`
3. Combined handoff table from `artifacts/handoff/`

Goal of this notebook:

- combine existing matrix + transformer signals
- build features for an MC-dropout Bayesian Neural Network
- predict final preference score
- estimate uncertainty
- later generate top product recommendations

In [1]:
from pathlib import Path
import json

import numpy as np
import pandas as pd

PROJECT_ROOT = Path("/Users/veerr_89/Work/projects/up-skin")
ARTIFACT_DIR = PROJECT_ROOT / "artifacts"

MATRIX_DIR = ARTIFACT_DIR / "matrix"
TRANSFORMER_DIR = ARTIFACT_DIR / "transformer"
HANDOFF_DIR = ARTIFACT_DIR / "handoff"

required_paths = {
    "train_df": MATRIX_DIR / "train_df.csv",
    "test_df": MATRIX_DIR / "test_df.csv",
    "mf_predictions": MATRIX_DIR / "mf_predictions_test.csv",
    "matrix_metrics": MATRIX_DIR / "metrics.json",
    "product_catalog": TRANSFORMER_DIR / "product_catalog.csv",
    "product_embeddings": TRANSFORMER_DIR / "product_embeddings.npz",
    "hybrid_metrics": HANDOFF_DIR / "hybrid_metrics.json",
    "handoff_features": HANDOFF_DIR / "bayesian_handoff_features.csv",
    "run_config": ARTIFACT_DIR / "run_config.json",
}

missing = [name for name, path in required_paths.items() if not path.exists()]

if missing:
    raise FileNotFoundError(f"Missing required artifacts: {missing}")

print("All required Step 1-3 artifacts found.")
print(f"Project root: {PROJECT_ROOT}")

All required Step 1-3 artifacts found.
Project root: /Users/veerr_89/Work/projects/up-skin

In [2]:
train_df = pd.read_csv(required_paths["train_df"])
test_df = pd.read_csv(required_paths["test_df"])
mf_predictions = pd.read_csv(required_paths["mf_predictions"])
product_catalog = pd.read_csv(required_paths["product_catalog"])
handoff = pd.read_csv(required_paths["handoff_features"])

with open(required_paths["matrix_metrics"], "r") as f:
    matrix_metrics = json.load(f)

with open(required_paths["hybrid_metrics"], "r") as f:
    hybrid_metrics = json.load(f)

with open(required_paths["run_config"], "r") as f:
    run_config = json.load(f)

embedding_data = np.load(required_paths["product_embeddings"], allow_pickle=True)

print("Embedding file keys:", embedding_data.files)

product_ids_from_embeddings = embedding_data["product_ids"].astype(str)
product_embeddings = embedding_data["embeddings"]

summary = pd.DataFrame(
    {
        "artifact": [
            "train_df",
            "test_df",
            "mf_predictions",
            "product_catalog",
            "handoff",
            "product_embeddings",
        ],
        "rows": [
            len(train_df),
            len(test_df),
            len(mf_predictions),
            len(product_catalog),
            len(handoff),
            product_embeddings.shape[0],
        ],
        "columns_or_dim": [
            train_df.shape[1],
            test_df.shape[1],
            mf_predictions.shape[1],
            product_catalog.shape[1],
            handoff.shape[1],
            product_embeddings.shape[1],
        ],
    }
)

summary

Embedding file keys: ['product_ids', 'embeddings', 'model_name']

/var/folders/57/vnd70s_n33xdwqkg8pdrndwc0000gn/T/ipykernel_27885/2970724406.py:5: DtypeWarning: Columns (0: author_id) have mixed types. Specify dtype option on import or set low_memory=False.
  handoff = pd.read_csv(required_paths["handoff_features"])

             artifact    rows  columns_or_dim
0            train_df  121096               3
1             test_df   27822               3
2      mf_predictions   55640              23
3     product_catalog    2420              32
4             handoff   55640              43
5  product_embeddings    2420             384

All required Step 1-3 artifacts loaded successfully.
The matrix test set, MF prediction table, and Bayesian handoff table all have 7017 rows, so the handoff appears aligned with the held-out evaluation set.
The product catalog has 2420 skincare products, and the embedding matrix also has 2420 rows, so every catalog product should have one transformer embedding.
The transformer embedding dimension is 384, matching sentence-transformers/all-MiniLM-L6-v2.
The embedding file contains product_ids, embeddings, and model_name, so we can validate ID alignment before feature engineering.

# Step 2: Artifact Alignment Validation

In [3]:

required_handoff_columns = [
    "author_id",
    "product_id",
    "true_rating",
    "mf_score",
    "content_score",
    "content_rating_score",
    "hybrid_score",
    "mf_content_gap",
    "user_rating_count",
    "mean_user_rating",
    "profile_product_count",
    "liked_product_count",
    "mean_train_rating",
    "product_name",
    "brand_name",
    "secondary_category",
    "tertiary_category",
    "price_usd",
    "avg_product_rating",
    "num_reviews",
    "loves_count",
]

missing_handoff_columns = [
    col for col in required_handoff_columns if col not in handoff.columns
]

catalog_product_ids = product_catalog["product_id"].astype(str).to_numpy()
handoff_product_ids = handoff["product_id"].astype(str)
mf_product_ids = mf_predictions["product_id"].astype(str)

embedding_catalog_alignment = np.array_equal(
    catalog_product_ids,
    product_ids_from_embeddings,
)

handoff_pairs = set(
    zip(
        handoff["author_id"].astype(str),
        handoff["product_id"].astype(str),
    )
)

mf_pairs = set(
    zip(
        mf_predictions["author_id"].astype(str),
        mf_predictions["product_id"].astype(str),
    )
)

alignment_report = {
    "missing_handoff_columns": missing_handoff_columns,
    "handoff_rows": len(handoff),
    "mf_prediction_rows": len(mf_predictions),
    "handoff_unique_user_product_pairs": len(handoff_pairs),
    "mf_unique_user_product_pairs": len(mf_pairs),
    "handoff_pairs_match_mf_pairs": handoff_pairs == mf_pairs,
    "catalog_rows": len(product_catalog),
    "embedding_rows": product_embeddings.shape[0],
    "embedding_dim": product_embeddings.shape[1],
    "embedding_catalog_product_ids_match": embedding_catalog_alignment,
    "handoff_products_missing_from_catalog": int(
        (~handoff_product_ids.isin(product_catalog["product_id"].astype(str))).sum()
    ),
    "mf_products_missing_from_catalog": int(
        (~mf_product_ids.isin(product_catalog["product_id"].astype(str))).sum()
    ),
    "duplicate_handoff_pairs": int(
        handoff.duplicated(subset=["author_id", "product_id"]).sum()
    ),
    "duplicate_mf_prediction_pairs": int(
        mf_predictions.duplicated(subset=["author_id", "product_id"]).sum()
    ),
}

alignment_report

{'missing_handoff_columns': [],
 'handoff_rows': 55640,
 'mf_prediction_rows': 55640,
 'handoff_unique_user_product_pairs': 55640,
 'mf_unique_user_product_pairs': 55640,
 'handoff_pairs_match_mf_pairs': True,
 'catalog_rows': 2420,
 'embedding_rows': 2420,
 'embedding_dim': 384,
 'embedding_catalog_product_ids_match': True,
 'handoff_products_missing_from_catalog': 0,
 'mf_products_missing_from_catalog': 0,
 'duplicate_handoff_pairs': 0,
 'duplicate_mf_prediction_pairs': 0}

The Step 1-3 artifacts are perfectly aligned.
Every handoff row has a matching MF prediction row.
Every product in the handoff and MF prediction tables exists in the product catalog.
The transformer embedding matrix matches the catalog exactly: 2420 products and 384 dimensions.
There are no duplicate user-product pairs, so the table is safe to use as the base BNN modeling dataset.
Since missing_handoff_columns is empty, we can now inspect data quality, missing values, and current baseline performance.

# Step 3: Baseline Metrics And Missingness Audit

In [4]:
from IPython.display import display

modeling_numeric_columns = [
    "true_rating",
    "mf_score",
    "content_score",
    "content_rating_score",
    "hybrid_score",
    "mf_content_gap",
    "user_rating_count",
    "mean_user_rating",
    "profile_product_count",
    "liked_product_count",
    "mean_train_rating",
    "price_usd",
    "avg_product_rating",
    "num_reviews",
    "loves_count",
]

modeling_categorical_columns = [
    "brand_name",
    "secondary_category",
    "tertiary_category",
]

all_modeling_columns = modeling_numeric_columns + modeling_categorical_columns

missing_report = (
    handoff[all_modeling_columns]
    .isna()
    .sum()
    .reset_index()
    .rename(columns={"index": "column", 0: "missing_count"})
)

missing_report["missing_pct"] = (
    100 * missing_report["missing_count"] / len(handoff)
).round(2)

missing_report = missing_report.sort_values(
    ["missing_count", "column"],
    ascending=[False, True],
).reset_index(drop=True)

numeric_summary = (
    handoff[modeling_numeric_columns]
    .describe()
    .T[["count", "mean", "std", "min", "25%", "50%", "75%", "max"]]
    .round(4)
)

score_range_checks = pd.DataFrame(
    {
        "score_column": [
            "true_rating",
            "mf_score",
            "content_rating_score",
            "hybrid_score",
        ],
        "expected_min": [1, 1, 1, 1],
        "expected_max": [5, 5, 5, 5],
        "actual_min": [
            handoff["true_rating"].min(),
            handoff["mf_score"].min(),
            handoff["content_rating_score"].min(),
            handoff["hybrid_score"].min(),
        ],
        "actual_max": [
            handoff["true_rating"].max(),
            handoff["mf_score"].max(),
            handoff["content_rating_score"].max(),
            handoff["hybrid_score"].max(),
        ],
    }
)

score_range_checks["inside_expected_range"] = (
    (score_range_checks["actual_min"] >= score_range_checks["expected_min"])
    & (score_range_checks["actual_max"] <= score_range_checks["expected_max"])
)

rating_metric_rows = []

for model_key in [
    "global_mean",
    "user_item_baseline",
    "biased_mf",
    "content_only",
    "hybrid",
]:
    payload = hybrid_metrics.get(model_key, matrix_metrics.get(model_key, {}))
    if isinstance(payload, dict) and "rmse" in payload:
        rating_metric_rows.append(
            {
                "model": model_key,
                "rmse": payload.get("rmse"),
                "mae": payload.get("mae"),
                "evaluated_rows": payload.get("evaluated_rows", len(handoff)),
                "alpha": payload.get("alpha", np.nan),
            }
        )

rating_metrics_table = pd.DataFrame(rating_metric_rows).round(4)

ranking_metric_rows = []

for model_name, payload in hybrid_metrics.get("ranking", {}).items():
    if not isinstance(payload, dict):
        continue

    row = {"model": model_name}
    for key, value in payload.items():
        if key.startswith("hit_rate_at_") or key == "evaluated_users":
            row[key] = value
    ranking_metric_rows.append(row)

ranking_metrics_table = pd.DataFrame(ranking_metric_rows).round(4)

print("Missing value report:")
display(missing_report)

print("Numeric modeling summary:")
display(numeric_summary)

print("Score range checks:")
display(score_range_checks)

print("Current rating metrics:")
display(rating_metrics_table)

print("Current ranking metrics:")
display(ranking_metrics_table)

print("Decision gate from previous pipeline:")
display(hybrid_metrics.get("decision_gate", {}))

Missing value report:

                   column  missing_count  missing_pct
0       tertiary_category           6961        12.51
1      avg_product_rating              0         0.00
2              brand_name              0         0.00
3    content_rating_score              0         0.00
4           content_score              0         0.00
5            hybrid_score              0         0.00
6     liked_product_count              0         0.00
7             loves_count              0         0.00
8       mean_train_rating              0         0.00
9        mean_user_rating              0         0.00
10         mf_content_gap              0         0.00
11               mf_score              0         0.00
12            num_reviews              0         0.00
13              price_usd              0         0.00
14  profile_product_count              0         0.00
15     secondary_category              0         0.00
16            true_rating              0         0.00
17      user_rating_count              0         0.00

Numeric modeling summary:

,count,mean,std,min,25%,50%,75%,max
true_rating,55640.0,4.4767,0.9618,1.0000,4.0000,5.0000,5.0000,5.000000e+00
mf_score,55640.0,4.4770,0.5551,1.1960,4.2210,4.6748,4.8979,5.000000e+00
content_score,55640.0,0.8092,0.0791,0.2095,0.7908,0.8296,0.8565,9.946000e-01
content_rating_score,55640.0,4.2367,0.3165,1.8381,4.1631,4.3182,4.4260,4.978400e+00
hybrid_score,55640.0,4.4049,0.4164,1.8846,4.2084,4.5354,4.7208,4.936900e+00
mf_content_gap,55640.0,0.5124,0.3736,0.0000,0.2655,0.4631,0.6435,3.435900e+00
user_rating_count,55640.0,20.5303,18.5483,4.0000,8.0000,13.0000,26.0000,2.000000e+02
mean_user_rating,55640.0,4.4678,0.5832,1.0000,4.1667,4.6591,4.9394,5.000000e+00
profile_product_count,55640.0,18.5093,17.6477,1.0000,7.0000,12.0000,24.0000,1.750000e+02
liked_product_count,55640.0,18.4915,17.6622,0.0000,7.0000,11.0000,24.0000,1.750000e+02
mean_train_rating,55640.0,4.4678,0.5832,1.0000,4.1667,4.6591,4.9394,5.000000e+00
price_usd,55640.0,56.3375,47.8298,3.0000,30.0000,45.0000,68.0000,4.490000e+02
avg_product_rating,55640.0,4.4074,0.2802,2.2820,4.2460,4.4532,4.6058,5.000000e+00
num_reviews,55640.0,1559.6281,1850.8169,1.0000,384.0000,922.0000,2052.0000,1.611800e+04
loves_count,55640.0,72964.6055,114204.6872,0.0000,11425.0000,30022.0000,93009.0000,1.081315e+06

Score range checks:

,score_column,expected_min,expected_max,actual_min,actual_max,inside_expected_range
0,true_rating,1,5,1.000000,5.000000,True
1,mf_score,1,5,1.195981,5.000000,True
2,content_rating_score,1,5,1.838064,4.978403,True
3,hybrid_score,1,5,1.884647,4.936855,True

Current rating metrics:

          model    rmse     mae  evaluated_rows  alpha
0     biased_mf  0.7807  0.4912           27822    NaN
1  content_only  1.0058  0.8139           55640    NaN
2        hybrid  0.8021  0.5771           55640    0.7

Current ranking metrics:

     model  hit_rate_at_5  hit_rate_at_10  hit_rate_at_20  evaluated_users
0       mf            NaN             NaN             NaN              NaN
1  content          0.019          0.0287          0.0434           9246.0

Decision gate from previous pipeline:

{'content_beats_mf_hit_rate_at_10': False, 'hybrid_beats_mf_rmse': False}

The modeling table is usable: all score columns and numeric metadata are complete.
Only tertiary_category has missing values: 919 rows, or 13.1%. This is manageable; we should encode missing values as "Unknown" instead of dropping rows.
Ratings are heavily positive: median true_rating is 5.0, so the BNN must be judged against a strong MF baseline, not just raw accuracy.
MF is currently the best rating predictor: RMSE 0.7932, MAE 0.4986.
Content-only is weaker for exact rating prediction: RMSE 1.0174, but it is better for ranking.
Content beats MF on HitRate@10: 0.0329 vs 0.0101, so the transformer signal is valuable even though it is poorly calibrated as a rating score.
Hybrid at alpha 0.7 is worse than MF for RMSE, so the BNN should learn when to trust MF vs content rather than use a fixed weighted average.

# Step 4: Prepare Versioned Modeling Table

In [5]:
from datetime import datetime
from pathlib import Path
import json

VERSION_ROOT = ARTIFACT_DIR / "versions"
VERSION_ROOT.mkdir(parents=True, exist_ok=True)

CURRENT_RUN_PATH = ARTIFACT_DIR / "current_run.json"

if CURRENT_RUN_PATH.exists():
    current_run = json.loads(CURRENT_RUN_PATH.read_text())
    RUN_ID = current_run["run_id"]
    RUN_DIR = Path(current_run["run_dir"])
    print("Reusing full-pipeline run:", RUN_ID)
else:
    existing_versions = sorted(
        p.name for p in VERSION_ROOT.glob("v*")
        if p.is_dir() and p.name[1:].isdigit()
    )
    RUN_ID = f"v{(int(existing_versions[-1][1:]) + 1 if existing_versions else 1):03d}"
    RUN_DIR = VERSION_ROOT / RUN_ID
    current_run = {
        "run_id": RUN_ID,
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "run_dir": str(RUN_DIR),
    }
    CURRENT_RUN_PATH.write_text(json.dumps(current_run, indent=2, sort_keys=True) + "\n")
    print("Created fallback BNN run:", RUN_ID)

STEP4_DIR = RUN_DIR / "step4_features"
STEP4_DIR.mkdir(parents=True, exist_ok=True)


modeling_df = handoff.copy()

# Keep IDs as strings so joins and exports stay stable.
modeling_df["author_id"] = modeling_df["author_id"].astype(str)
modeling_df["product_id"] = modeling_df["product_id"].astype(str)

# Fill categorical missingness without dropping usable rows.
categorical_fill_columns = [
    "brand_name",
    "secondary_category",
    "tertiary_category",
]

for col in categorical_fill_columns:
    modeling_df[col] = (
        modeling_df[col]
        .fillna("Unknown")
        .astype(str)
        .str.strip()
        .replace({"": "Unknown", "nan": "Unknown"})
    )

# Add log transforms for skewed metadata fields.
# These keep raw values available while giving the model smoother inputs.
for col in ["price_usd", "num_reviews", "loves_count"]:
    modeling_df[f"log1p_{col}"] = np.log1p(modeling_df[col].clip(lower=0))

# Add simple reliability/context features.
modeling_df["has_liked_history"] = (modeling_df["liked_product_count"] > 0).astype(int)
modeling_df["user_history_strength"] = np.log1p(modeling_df["user_rating_count"])
modeling_df["profile_history_strength"] = np.log1p(modeling_df["profile_product_count"])

run_metadata = {
    "run_id": RUN_ID,
    "created_at": datetime.now().isoformat(timespec="seconds"),
    "source_handoff_rows": int(len(handoff)),
    "modeling_rows": int(len(modeling_df)),
    "source_embedding_rows": int(product_embeddings.shape[0]),
    "source_embedding_dim": int(product_embeddings.shape[1]),
    "notes": "Step 4 prepared modeling table from completed matrix + transformer handoff artifacts.",
}

category_cardinality = pd.DataFrame(
    {
        "column": categorical_fill_columns,
        "unique_values": [
            modeling_df[col].nunique()
            for col in categorical_fill_columns
        ],
        "top_value": [
            modeling_df[col].value_counts().idxmax()
            for col in categorical_fill_columns
        ],
        "top_value_count": [
            int(modeling_df[col].value_counts().max())
            for col in categorical_fill_columns
        ],
    }
)

new_columns = [
    "log1p_price_usd",
    "log1p_num_reviews",
    "log1p_loves_count",
    "has_liked_history",
    "user_history_strength",
    "profile_history_strength",
]

step4_preview = modeling_df[
    [
        "author_id",
        "product_id",
        "true_rating",
        "mf_score",
        "content_score",
        "content_rating_score",
        "hybrid_score",
        "secondary_category",
        "tertiary_category",
        *new_columns,
    ]
].head()

print(f"Created run folder: {RUN_DIR}")
print(f"Run ID: {RUN_ID}")
print(f"Modeling table shape: {modeling_df.shape}")

print("\nRun metadata:")
display(run_metadata)

print("\nCategorical cardinality:")
display(category_cardinality)

print("\nStep 4 modeling preview:")
display(step4_preview)

Reusing full-pipeline run: v002
Created run folder: /Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002
Run ID: v002
Modeling table shape: (55640, 49)

Run metadata:

{'run_id': 'v002',
 'created_at': '2026-05-05T23:38:36',
 'source_handoff_rows': 55640,
 'modeling_rows': 55640,
 'source_embedding_rows': 2420,
 'source_embedding_dim': 384,
 'notes': 'Step 4 prepared modeling table from completed matrix + transformer handoff artifacts.'}

Categorical cardinality:

               column  unique_values     top_value  top_value_count
0          brand_name            137   Glow Recipe             2725
1  secondary_category             12  Moisturizers            15302
2   tertiary_category             31  Moisturizers            10980

Step 4 modeling preview:

,author_id,product_id,true_rating,mf_score,content_score,content_rating_score,hybrid_score,secondary_category,tertiary_category,log1p_price_usd,log1p_num_reviews,log1p_loves_count,has_liked_history,user_history_strength,profile_history_strength
0,10000770719,P404338,4.0,4.849577,0.808294,4.233176,4.664656,Moisturizers,Moisturizers,3.828641,7.239933,10.607031,1,2.302585,2.302585
1,10000770719,P454936,5.0,4.823746,0.773950,4.095801,4.605362,Mini Size,Unknown,4.709530,6.779922,8.453614,1,2.302585,2.302585
2,1000235057,P454799,1.0,3.021674,0.543337,3.173348,3.067176,Mini Size,Unknown,3.258097,6.204558,8.578100,1,3.295837,2.833213
3,1000235057,P427414,4.0,3.537052,0.843055,4.372221,3.787603,Treatments,Face Serums,2.014903,7.627057,12.462485,1,3.295837,2.833213
4,1000235057,P416552,3.0,4.302204,0.817662,4.270647,4.292737,Treatments,Face Serums,4.564348,5.327876,9.292842,1,3.295837,2.833213

- Versioned run `v001` was created successfully, so this notebook can now track results across future model versions.
- The modeling table still has all `7017` rows, so no data was lost while preparing Step 4 features.
- The table expanded from `25` to `31` columns because we added 6 engineered features:
  - `log1p_price_usd`
  - `log1p_num_reviews`
  - `log1p_loves_count`
  - `has_liked_history`
  - `user_history_strength`
  - `profile_history_strength`
- Missing `tertiary_category` values were handled correctly as `Unknown`, visible in the preview.
- `secondary_category` and `tertiary_category` have manageable cardinality, but `brand_name` has `124` unique values, so later we should group rare brands before one-hot encoding.
- Next, we should reuse the transformer product embeddings from Step 3, reduce them from `384` dimensions, and join them into this modeling table.

# Step 5: Add Reduced Transformer Embedding Features

In [6]:
from sklearn.decomposition import PCA

EMBEDDING_COMPONENTS = 32

embedding_df = pd.DataFrame(
    product_embeddings,
    columns=[f"raw_embedding_{i:03d}" for i in range(product_embeddings.shape[1])]
)

embedding_df.insert(0, "product_id", product_ids_from_embeddings.astype(str))

pca = PCA(
    n_components=EMBEDDING_COMPONENTS,
    random_state=run_config.get("random_state", 42),
)

reduced_embeddings = pca.fit_transform(product_embeddings)

reduced_embedding_columns = [
    f"embedding_pca_{i + 1:02d}"
    for i in range(EMBEDDING_COMPONENTS)
]

reduced_embedding_df = pd.DataFrame(
    reduced_embeddings,
    columns=reduced_embedding_columns,
)

reduced_embedding_df.insert(0, "product_id", product_ids_from_embeddings.astype(str))

modeling_with_embeddings_df = modeling_df.merge(
    reduced_embedding_df,
    on="product_id",
    how="left",
    validate="many_to_one",
)

embedding_join_missing = (
    modeling_with_embeddings_df[reduced_embedding_columns]
    .isna()
    .any(axis=1)
    .sum()
)

pca_summary = pd.DataFrame(
    {
        "component": reduced_embedding_columns,
        "explained_variance_ratio": pca.explained_variance_ratio_,
        "cumulative_explained_variance": np.cumsum(pca.explained_variance_ratio_),
    }
)

embedding_join_report = {
    "original_modeling_shape": modeling_df.shape,
    "modeling_with_embeddings_shape": modeling_with_embeddings_df.shape,
    "raw_embedding_dim": int(product_embeddings.shape[1]),
    "reduced_embedding_dim": EMBEDDING_COMPONENTS,
    "embedding_join_missing_rows": int(embedding_join_missing),
    "pca_total_explained_variance": float(pca.explained_variance_ratio_.sum()),
}

print("Embedding join report:")
display(embedding_join_report)

print("\nPCA explained variance summary:")
display(pca_summary.head(10))

print("\nFinal cumulative explained variance:")
display(pca_summary.tail(1))

print("\nPreview with reduced embedding columns:")
display(
    modeling_with_embeddings_df[
        [
            "author_id",
            "product_id",
            "true_rating",
            "mf_score",
            "content_score",
            "hybrid_score",
            *reduced_embedding_columns[:5],
        ]
    ].head()
)

Embedding join report:

{'original_modeling_shape': (55640, 49),
 'modeling_with_embeddings_shape': (55640, 81),
 'raw_embedding_dim': 384,
 'reduced_embedding_dim': 32,
 'embedding_join_missing_rows': 0,
 'pca_total_explained_variance': 0.6157936453819275}

PCA explained variance summary:

          component  explained_variance_ratio  cumulative_explained_variance
0  embedding_pca_01                  0.085773                       0.085773
1  embedding_pca_02                  0.057163                       0.142936
2  embedding_pca_03                  0.037784                       0.180720
3  embedding_pca_04                  0.034793                       0.215513
4  embedding_pca_05                  0.033301                       0.248815
5  embedding_pca_06                  0.030947                       0.279762
6  embedding_pca_07                  0.028559                       0.308321
7  embedding_pca_08                  0.025220                       0.333541
8  embedding_pca_09                  0.020629                       0.354170
9  embedding_pca_10                  0.019216                       0.373386

Final cumulative explained variance:

           component  explained_variance_ratio  cumulative_explained_variance
31  embedding_pca_32                  0.007392                       0.615794

Preview with reduced embedding columns:

,author_id,product_id,true_rating,mf_score,content_score,hybrid_score,embedding_pca_01,embedding_pca_02,embedding_pca_03,embedding_pca_04,embedding_pca_05
0,10000770719,P404338,4.0,4.849577,0.808294,4.664656,0.146748,0.088754,0.023424,-0.017315,-0.027771
1,10000770719,P454936,5.0,4.823746,0.773950,4.605362,-0.202884,-0.167857,-0.103034,0.074461,0.075060
2,1000235057,P454799,1.0,3.021674,0.543337,3.067176,-0.100202,0.184674,-0.100607,-0.099821,-0.167347
3,1000235057,P427414,4.0,3.537052,0.843055,3.787603,0.050198,-0.093317,-0.003063,0.210840,0.020120
4,1000235057,P416552,3.0,4.302204,0.817662,4.292737,0.136766,-0.062814,-0.105655,-0.018402,0.005671

- The transformer embeddings joined cleanly into the modeling table: `0` rows are missing embedding features.
- The modeling table expanded from `31` to `63` columns, which means all `32` PCA embedding features were added successfully.
- PCA reduced the original `384` transformer dimensions down to `32`, while preserving about `61.6%` of total embedding variance.
- This is a reasonable first compression level: it keeps substantial product-content signal without overwhelming a dataset of only `7017` rows.
- The first few PCA columns contain varied positive and negative values, which is expected after PCA and confirms these are dense continuous features, not category indicators.
- Next, we should define the BNN input feature set, group rare brands, and create train/validation/test splits before scaling and model training.

# Step 6: Build Feature Schema And Data Splits

In [7]:
from sklearn.model_selection import GroupShuffleSplit

bnn_df = modeling_with_embeddings_df.copy()

TARGET_COLUMN = "true_rating"
ID_COLUMNS = ["author_id", "product_id"]

base_numeric_features = [
    "mf_score",
    "content_score",
    "content_rating_score",
    "hybrid_score",
    "mf_content_gap",
    "user_rating_count",
    "mean_user_rating",
    "profile_product_count",
    "liked_product_count",
    "mean_train_rating",
    "price_usd",
    "avg_product_rating",
    "num_reviews",
    "loves_count",
    "log1p_price_usd",
    "log1p_num_reviews",
    "log1p_loves_count",
    "has_liked_history",
    "user_history_strength",
    "profile_history_strength",
]

optional_ensemble_numeric_features = [
    "baseline_score",
    "legacy_mf_score",
    "item_knn_score",
    "metadata_content_score",
    "ridge_ensemble_score",
    "gb_ensemble_score",
    "rf_ensemble_score",
    "product_rating_count",
    "product_avg_rating",
    "pred_mean",
    "pred_std",
    "pred_min",
    "pred_max",
    "pred_range",
    "component_score_mean",
    "component_score_std",
    "component_score_range",
]

base_numeric_features += [
    col for col in optional_ensemble_numeric_features
    if col in bnn_df.columns and col not in base_numeric_features
]

numeric_features = base_numeric_features + reduced_embedding_columns

TOP_BRAND_COUNT = 25

top_brands = (
    bnn_df["brand_name"]
    .value_counts()
    .head(TOP_BRAND_COUNT)
    .index
)

bnn_df["brand_name_grouped"] = np.where(
    bnn_df["brand_name"].isin(top_brands),
    bnn_df["brand_name"],
    "Other Brand",
)

categorical_features = [
    "brand_name_grouped",
    "secondary_category",
    "tertiary_category",
]

feature_columns = numeric_features + categorical_features

missing_feature_columns = [
    col for col in feature_columns + [TARGET_COLUMN, *ID_COLUMNS]
    if col not in bnn_df.columns
]

if missing_feature_columns:
    raise ValueError(f"Missing expected columns: {missing_feature_columns}")

if bnn_df[feature_columns].isna().sum().sum() > 0:
    missing_by_column = bnn_df[feature_columns].isna().sum()
    raise ValueError(
        "Feature table still has missing values:\n"
        + missing_by_column[missing_by_column > 0].to_string()
    )

# If the Ridge ensemble export added source_split, keep the final upstream test
# rows as the final BNN test set. Split only upstream validation rows into BNN
# train/validation.
if "source_split" in bnn_df.columns:
    bnn_trainval_df = bnn_df[bnn_df["source_split"] == "validation"].reset_index(drop=True)
    test_df_bnn = bnn_df[bnn_df["source_split"] == "test"].reset_index(drop=True)

    if bnn_trainval_df.empty or test_df_bnn.empty:
        raise ValueError(
            "source_split exists, but expected both 'validation' and 'test' rows."
        )

    splitter = GroupShuffleSplit(
        n_splits=1,
        test_size=0.20,
        random_state=run_config.get("random_state", 42),
    )

    train_idx, val_idx = next(
        splitter.split(
            bnn_trainval_df,
            bnn_trainval_df[TARGET_COLUMN],
            groups=bnn_trainval_df["author_id"].astype(str),
        )
    )

    train_df_bnn = bnn_trainval_df.iloc[train_idx].reset_index(drop=True)
    val_df_bnn = bnn_trainval_df.iloc[val_idx].reset_index(drop=True)

else:
    groups = bnn_df["author_id"].astype(str)

    splitter_1 = GroupShuffleSplit(
        n_splits=1,
        test_size=0.30,
        random_state=run_config.get("random_state", 42),
    )

    train_idx, temp_idx = next(
        splitter_1.split(
            bnn_df,
            bnn_df[TARGET_COLUMN],
            groups=groups,
        )
    )

    train_df_bnn = bnn_df.iloc[train_idx].reset_index(drop=True)
    temp_df_bnn = bnn_df.iloc[temp_idx].reset_index(drop=True)

    splitter_2 = GroupShuffleSplit(
        n_splits=1,
        test_size=0.50,
        random_state=run_config.get("random_state", 42) + 1,
    )

    val_idx, test_idx = next(
        splitter_2.split(
            temp_df_bnn,
            temp_df_bnn[TARGET_COLUMN],
            groups=temp_df_bnn["author_id"].astype(str),
        )
    )

    val_df_bnn = temp_df_bnn.iloc[val_idx].reset_index(drop=True)
    test_df_bnn = temp_df_bnn.iloc[test_idx].reset_index(drop=True)

split_report = {
    "total_rows": int(len(bnn_df)),
    "train_rows": int(len(train_df_bnn)),
    "val_rows": int(len(val_df_bnn)),
    "test_rows": int(len(test_df_bnn)),
    "train_users": int(train_df_bnn["author_id"].nunique()),
    "val_users": int(val_df_bnn["author_id"].nunique()),
    "test_users": int(test_df_bnn["author_id"].nunique()),
    "numeric_feature_count": int(len(numeric_features)),
    "categorical_feature_count": int(len(categorical_features)),
    "total_pre_encoding_feature_count": int(len(feature_columns)),
    "top_brand_count": int(TOP_BRAND_COUNT),
    "uses_upstream_source_split": bool("source_split" in bnn_df.columns),
}

if "source_split" in bnn_df.columns:
    split_report["source_split_counts"] = (
        bnn_df["source_split"].value_counts().to_dict()
    )

overlap_report = {
    "train_val_user_overlap": int(
        len(set(train_df_bnn["author_id"]) & set(val_df_bnn["author_id"]))
    ),
    "train_test_user_overlap": int(
        len(set(train_df_bnn["author_id"]) & set(test_df_bnn["author_id"]))
    ),
    "val_test_user_overlap": int(
        len(set(val_df_bnn["author_id"]) & set(test_df_bnn["author_id"]))
    ),
}

target_distribution = pd.DataFrame(
    {
        "split": ["train", "validation", "test"],
        "rows": [len(train_df_bnn), len(val_df_bnn), len(test_df_bnn)],
        "mean_rating": [
            train_df_bnn[TARGET_COLUMN].mean(),
            val_df_bnn[TARGET_COLUMN].mean(),
            test_df_bnn[TARGET_COLUMN].mean(),
        ],
        "std_rating": [
            train_df_bnn[TARGET_COLUMN].std(),
            val_df_bnn[TARGET_COLUMN].std(),
            test_df_bnn[TARGET_COLUMN].std(),
        ],
        "pct_5_star": [
            100 * (train_df_bnn[TARGET_COLUMN] == 5).mean(),
            100 * (val_df_bnn[TARGET_COLUMN] == 5).mean(),
            100 * (test_df_bnn[TARGET_COLUMN] == 5).mean(),
        ],
    }
).round(4)

print("Split report:")
display(split_report)

print("\nUser overlap report:")
display(overlap_report)

print("\nTarget distribution by split:")
display(target_distribution)

print("\nNumeric features:")
display(numeric_features)

print("\nCategorical features:")
display(categorical_features)

Split report:

{'total_rows': 55640,
 'train_rows': 22299,
 'val_rows': 5519,
 'test_rows': 27822,
 'train_users': 7396,
 'val_users': 1850,
 'test_users': 9246,
 'numeric_feature_count': 69,
 'categorical_feature_count': 3,
 'total_pre_encoding_feature_count': 72,
 'top_brand_count': 25,
 'uses_upstream_source_split': True,
 'source_split_counts': {'test': 27822, 'validation': 27818}}

User overlap report:

{'train_val_user_overlap': 0,
 'train_test_user_overlap': 7396,
 'val_test_user_overlap': 1850}

Target distribution by split:

        split   rows  mean_rating  std_rating  pct_5_star
0       train  22299       4.4708      0.9661     68.9762
1  validation   5519       4.5120      0.9276     70.9730
2        test  27822       4.4745      0.9649     69.2402

Numeric features:

['mf_score',
 'content_score',
 'content_rating_score',
 'hybrid_score',
 'mf_content_gap',
 'user_rating_count',
 'mean_user_rating',
 'profile_product_count',
 'liked_product_count',
 'mean_train_rating',
 'price_usd',
 'avg_product_rating',
 'num_reviews',
 'loves_count',
 'log1p_price_usd',
 'log1p_num_reviews',
 'log1p_loves_count',
 'has_liked_history',
 'user_history_strength',
 'profile_history_strength',
 'baseline_score',
 'legacy_mf_score',
 'item_knn_score',
 'metadata_content_score',
 'ridge_ensemble_score',
 'gb_ensemble_score',
 'rf_ensemble_score',
 'product_rating_count',
 'product_avg_rating',
 'pred_mean',
 'pred_std',
 'pred_min',
 'pred_max',
 'pred_range',
 'component_score_mean',
 'component_score_std',
 'component_score_range',
 'embedding_pca_01',
 'embedding_pca_02',
 'embedding_pca_03',
 'embedding_pca_04',
 'embedding_pca_05',
 'embedding_pca_06',
 'embedding_pca_07',
 'embedding_pca_08',
 'embedding_pca_09',
 'embedding_pca_10',
 'embedding_pca_11',
 'embedding_pca_12',
 'embedding_pca_13',
 'embedding_pca_14',
 'embedding_pca_15',
 'embedding_pca_16',
 'embedding_pca_17',
 'embedding_pca_18',
 'embedding_pca_19',
 'embedding_pca_20',
 'embedding_pca_21',
 'embedding_pca_22',
 'embedding_pca_23',
 'embedding_pca_24',
 'embedding_pca_25',
 'embedding_pca_26',
 'embedding_pca_27',
 'embedding_pca_28',
 'embedding_pca_29',
 'embedding_pca_30',
 'embedding_pca_31',
 'embedding_pca_32']

Categorical features:

['brand_name_grouped', 'secondary_category', 'tertiary_category']

- The split is healthy and reproducible: `4910` train rows, `1061` validation rows, and `1046` test rows.
- User leakage is avoided: train/validation/test user overlap is `0` in every pair.
- Rating distributions are very similar across splits:
  - train mean rating: `4.4507`
  - validation mean rating: `4.4694`
  - test mean rating: `4.4699`
- All splits are highly positive, with about `68-69%` 5-star ratings, so the BNN must beat strong high-rating baselines.
- The current feature design has `52` numeric features and `3` categorical features before one-hot encoding.
- The feature set is ready for preprocessing: scale numeric columns, one-hot encode categories, and compare MF/content/hybrid baselines on the same train/validation/test split.

# Step 7: Preprocess Features And Split Baselines

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

try:
    one_hot_encoder = OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False,
    )
except TypeError:
    one_hot_encoder = OneHotEncoder(
        handle_unknown="ignore",
        sparse=False,
    )

numeric_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Unknown")),
        ("onehot", one_hot_encoder),
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_pipeline, numeric_features),
        ("categorical", categorical_pipeline, categorical_features),
    ],
    remainder="drop",
    verbose_feature_names_out=True,
)

X_train = preprocessor.fit_transform(train_df_bnn[feature_columns])
X_val = preprocessor.transform(val_df_bnn[feature_columns])
X_test = preprocessor.transform(test_df_bnn[feature_columns])

X_train = np.asarray(X_train, dtype=np.float32)
X_val = np.asarray(X_val, dtype=np.float32)
X_test = np.asarray(X_test, dtype=np.float32)

y_train = train_df_bnn[TARGET_COLUMN].to_numpy(dtype=np.float32)
y_val = val_df_bnn[TARGET_COLUMN].to_numpy(dtype=np.float32)
y_test = test_df_bnn[TARGET_COLUMN].to_numpy(dtype=np.float32)

encoded_feature_names = preprocessor.get_feature_names_out()

def rmse_score(y_true, y_pred):
    return float(np.sqrt(mean_squared_error(y_true, y_pred)))

def evaluate_score_column(df, score_column, split_name):
    return {
        "split": split_name,
        "model": score_column,
        "rmse": rmse_score(df[TARGET_COLUMN], df[score_column]),
        "mae": float(mean_absolute_error(df[TARGET_COLUMN], df[score_column])),
        "pred_min": float(df[score_column].min()),
        "pred_mean": float(df[score_column].mean()),
        "pred_max": float(df[score_column].max()),
    }

baseline_metric_rows = []

for split_name, split_df in [
    ("train", train_df_bnn),
    ("validation", val_df_bnn),
    ("test", test_df_bnn),
]:
    for score_column in [
        "mf_score",
        "content_rating_score",
        "hybrid_score",
    ]:
        baseline_metric_rows.append(
            evaluate_score_column(split_df, score_column, split_name)
        )

split_baseline_metrics = pd.DataFrame(baseline_metric_rows).round(4)

preprocessing_report = {
    "train_matrix_shape": X_train.shape,
    "validation_matrix_shape": X_val.shape,
    "test_matrix_shape": X_test.shape,
    "encoded_feature_count": int(X_train.shape[1]),
    "raw_numeric_feature_count": int(len(numeric_features)),
    "raw_categorical_feature_count": int(len(categorical_features)),
    "train_target_mean": float(y_train.mean()),
    "validation_target_mean": float(y_val.mean()),
    "test_target_mean": float(y_test.mean()),
}

print("Preprocessing report:")
display(preprocessing_report)

print("\nSplit baseline metrics:")
display(split_baseline_metrics)

print("\nFirst 25 encoded feature names:")
display(list(encoded_feature_names[:25]))

print("\nLast 25 encoded feature names:")
display(list(encoded_feature_names[-25:]))

Preprocessing report:

{'train_matrix_shape': (22299, 138),
 'validation_matrix_shape': (5519, 138),
 'test_matrix_shape': (27822, 138),
 'encoded_feature_count': 138,
 'raw_numeric_feature_count': 69,
 'raw_categorical_feature_count': 3,
 'train_target_mean': 4.470805644989014,
 'validation_target_mean': 4.511958599090576,
 'test_target_mean': 4.47449254989624}

Split baseline metrics:

,split,model,rmse,mae,pred_min,pred_mean,pred_max
0,train,mf_score,0.7811,0.4957,1.2243,4.4706,5.0000
1,train,content_rating_score,1.0114,0.8179,1.8556,4.2352,4.9784
2,train,hybrid_score,0.8058,0.5814,2.0666,4.4000,4.9369
3,validation,mf_score,0.7578,0.4734,1.6370,4.4942,5.0000
4,validation,content_rating_score,0.9773,0.7976,2.0194,4.2386,4.7765
5,validation,hybrid_score,0.7774,0.5607,2.3735,4.4175,4.9048
6,test,mf_score,0.7807,0.4912,1.1960,4.4788,5.0000
7,test,content_rating_score,1.0069,0.8139,1.8381,4.2375,4.9747
8,test,hybrid_score,0.8040,0.5770,1.8846,4.4064,4.9294

First 25 encoded feature names:

['numeric__mf_score',
 'numeric__content_score',
 'numeric__content_rating_score',
 'numeric__hybrid_score',
 'numeric__mf_content_gap',
 'numeric__user_rating_count',
 'numeric__mean_user_rating',
 'numeric__profile_product_count',
 'numeric__liked_product_count',
 'numeric__mean_train_rating',
 'numeric__price_usd',
 'numeric__avg_product_rating',
 'numeric__num_reviews',
 'numeric__loves_count',
 'numeric__log1p_price_usd',
 'numeric__log1p_num_reviews',
 'numeric__log1p_loves_count',
 'numeric__has_liked_history',
 'numeric__user_history_strength',
 'numeric__profile_history_strength',
 'numeric__baseline_score',
 'numeric__legacy_mf_score',
 'numeric__item_knn_score',
 'numeric__metadata_content_score',
 'numeric__ridge_ensemble_score']

Last 25 encoded feature names:

['categorical__tertiary_category_Decollete & Neck Creams',
 'categorical__tertiary_category_Exfoliators',
 'categorical__tertiary_category_Eye Creams & Treatments',
 'categorical__tertiary_category_Eye Masks',
 'categorical__tertiary_category_Face Masks',
 'categorical__tertiary_category_Face Oils',
 'categorical__tertiary_category_Face Serums',
 'categorical__tertiary_category_Face Sunscreen',
 'categorical__tertiary_category_Face Wash & Cleansers',
 'categorical__tertiary_category_Face Wipes',
 'categorical__tertiary_category_Facial Cleansing Brushes',
 'categorical__tertiary_category_Facial Peels',
 'categorical__tertiary_category_Facial Rollers',
 'categorical__tertiary_category_For Body',
 'categorical__tertiary_category_For Face',
 'categorical__tertiary_category_Hair Removal',
 'categorical__tertiary_category_Holistic Wellness',
 'categorical__tertiary_category_Makeup Removers',
 'categorical__tertiary_category_Mists & Essences',
 'categorical__tertiary_category_Moisturizers',
 'categorical__tertiary_category_Night Creams',
 'categorical__tertiary_category_Sheet Masks',
 'categorical__tertiary_category_Teeth Whitening',
 'categorical__tertiary_category_Toners',
 'categorical__tertiary_category_Unknown']

- Preprocessing worked correctly: all three splits were transformed into model-ready matrices with `120` encoded features.
- The encoded feature count is reasonable: `52` numeric inputs plus one-hot categorical columns.
- The validation and test target means remain close to train, so the split is still balanced after preprocessing.
- MF remains the strongest baseline on this exact split:
  - validation RMSE: `0.7970`
  - test RMSE: `0.7786`
- Hybrid is close but slightly worse than MF:
  - validation RMSE: `0.8012`
  - test RMSE: `0.7922`
- Content-only remains worse for exact rating prediction, but we still keep its features because earlier ranking metrics showed content helps product discovery.
- The BNN’s first goal is to beat or match MF on RMSE/MAE while producing useful uncertainty.

# Step 8: Define MC-Dropout BNN Model

In [9]:

import random
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

SEED = run_config.get("random_state", 42)

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    DEVICE = torch.device("cuda")
elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
    DEVICE = torch.device("mps")
else:
    DEVICE = torch.device("cpu")

BATCH_SIZE = 128
DROPOUT_RATE = 0.20
HIDDEN_1 = 128
HIDDEN_2 = 64

X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)

X_val_tensor = torch.tensor(X_val, dtype=torch.float32)
y_val_tensor = torch.tensor(y_val, dtype=torch.float32).view(-1, 1)

X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
)

class MCDropoutBNN(nn.Module):
    def __init__(
        self,
        input_dim,
        hidden_1=128,
        hidden_2=64,
        dropout_rate=0.20,
    ):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(input_dim, hidden_1),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_1, hidden_2),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_2, 1),
        )

    def forward(self, x):
        raw_output = self.network(x)

        # Keep predictions on the original 1-5 rating scale.
        bounded_rating = 1.0 + 4.0 * torch.sigmoid(raw_output)

        return bounded_rating

input_dim = X_train.shape[1]

model = MCDropoutBNN(
    input_dim=input_dim,
    hidden_1=HIDDEN_1,
    hidden_2=HIDDEN_2,
    dropout_rate=DROPOUT_RATE,
).to(DEVICE)

total_parameters = sum(p.numel() for p in model.parameters())
trainable_parameters = sum(p.numel() for p in model.parameters() if p.requires_grad)

model.eval()

with torch.no_grad():
    sample_batch_X, sample_batch_y = next(iter(train_loader))
    sample_batch_X = sample_batch_X.to(DEVICE)
    sample_predictions = model(sample_batch_X).cpu().numpy().ravel()

model_report = {
    "device": str(DEVICE),
    "input_dim": int(input_dim),
    "hidden_1": HIDDEN_1,
    "hidden_2": HIDDEN_2,
    "dropout_rate": DROPOUT_RATE,
    "batch_size": BATCH_SIZE,
    "total_parameters": int(total_parameters),
    "trainable_parameters": int(trainable_parameters),
    "sample_prediction_min": float(sample_predictions.min()),
    "sample_prediction_mean": float(sample_predictions.mean()),
    "sample_prediction_max": float(sample_predictions.max()),
    "sample_target_min": float(sample_batch_y.numpy().min()),
    "sample_target_mean": float(sample_batch_y.numpy().mean()),
    "sample_target_max": float(sample_batch_y.numpy().max()),
}

print("MC-dropout BNN model report:")
display(model_report)

print("\nModel architecture:")
display(model)

MC-dropout BNN model report:

{'device': 'mps',
 'input_dim': 138,
 'hidden_1': 128,
 'hidden_2': 64,
 'dropout_rate': 0.2,
 'batch_size': 128,
 'total_parameters': 26113,
 'trainable_parameters': 26113,
 'sample_prediction_min': 2.826474189758301,
 'sample_prediction_mean': 2.9373769760131836,
 'sample_prediction_max': 3.068074941635132,
 'sample_target_min': 1.0,
 'sample_target_mean': 4.4453125,
 'sample_target_max': 5.0}

Model architecture:

MCDropoutBNN(
  (network): Sequential(
    (0): Linear(in_features=138, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=128, out_features=64, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.2, inplace=False)
    (6): Linear(in_features=64, out_features=1, bias=True)
  )
)

- The MC-dropout BNN architecture initialized successfully.
- The notebook is using Apple Silicon `mps`, so training should run faster than CPU.
- The model has `23,809` trainable parameters, which is reasonable for `4,910` training rows and `120` encoded features.
- The initial untrained predictions are around `3.0`, while the sample target mean is around `4.31`; this is expected because the model has not learned yet.
- The output layer correctly bounds predictions to the `1-5` rating scale using `1 + 4 * sigmoid(raw_output)`.
- Next, we should train the model with early stopping and compare its validation RMSE against the current MF baseline.

# Step 9: Train MC-Dropout BNN

In [10]:
import copy
import time

LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4
MAX_EPOCHS = 250
EARLY_STOPPING_PATIENCE = 30
MIN_DELTA = 1e-4

criterion = nn.MSELoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
)

def predict_deterministic(model, X_array, batch_size=512):
    model.eval()
    predictions = []

    with torch.no_grad():
        for start in range(0, len(X_array), batch_size):
            batch = torch.tensor(
                X_array[start:start + batch_size],
                dtype=torch.float32,
                device=DEVICE,
            )
            batch_predictions = model(batch).detach().cpu().numpy().ravel()
            predictions.append(batch_predictions)

    return np.concatenate(predictions)

def regression_metrics(y_true, y_pred):
    return {
        "rmse": float(np.sqrt(mean_squared_error(y_true, y_pred))),
        "mae": float(mean_absolute_error(y_true, y_pred)),
        "pred_min": float(np.min(y_pred)),
        "pred_mean": float(np.mean(y_pred)),
        "pred_max": float(np.max(y_pred)),
    }

training_history = []

best_val_rmse = np.inf
best_epoch = None
best_state_dict = None
epochs_without_improvement = 0

start_time = time.time()

for epoch in range(1, MAX_EPOCHS + 1):
    model.train()

    train_losses = []

    for batch_X, batch_y in train_loader:
        batch_X = batch_X.to(DEVICE)
        batch_y = batch_y.to(DEVICE)

        optimizer.zero_grad()

        batch_predictions = model(batch_X)
        loss = criterion(batch_predictions, batch_y)

        loss.backward()
        optimizer.step()

        train_losses.append(loss.item())

    train_predictions = predict_deterministic(model, X_train)
    val_predictions = predict_deterministic(model, X_val)

    train_metrics = regression_metrics(y_train, train_predictions)
    val_metrics = regression_metrics(y_val, val_predictions)

    epoch_record = {
        "epoch": epoch,
        "train_loss": float(np.mean(train_losses)),
        "train_rmse": train_metrics["rmse"],
        "train_mae": train_metrics["mae"],
        "val_rmse": val_metrics["rmse"],
        "val_mae": val_metrics["mae"],
        "val_pred_mean": val_metrics["pred_mean"],
    }

    training_history.append(epoch_record)

    improved = val_metrics["rmse"] < (best_val_rmse - MIN_DELTA)

    if improved:
        best_val_rmse = val_metrics["rmse"]
        best_epoch = epoch
        best_state_dict = copy.deepcopy(model.state_dict())
        epochs_without_improvement = 0
    else:
        epochs_without_improvement += 1

    if epoch == 1 or epoch % 10 == 0 or improved:
        print(
            f"Epoch {epoch:03d} | "
            f"train RMSE {train_metrics['rmse']:.4f} | "
            f"val RMSE {val_metrics['rmse']:.4f} | "
            f"val MAE {val_metrics['mae']:.4f}"
        )

    if epochs_without_improvement >= EARLY_STOPPING_PATIENCE:
        print(
            f"Early stopping at epoch {epoch}. "
            f"Best validation RMSE: {best_val_rmse:.4f} at epoch {best_epoch}."
        )
        break

training_seconds = time.time() - start_time

if best_state_dict is not None:
    model.load_state_dict(best_state_dict)

training_history_df = pd.DataFrame(training_history)

best_val_predictions = predict_deterministic(model, X_val)
best_train_predictions = predict_deterministic(model, X_train)

bnn_train_metrics = regression_metrics(y_train, best_train_predictions)
bnn_val_metrics = regression_metrics(y_val, best_val_predictions)

validation_baselines = (
    split_baseline_metrics[split_baseline_metrics["split"] == "validation"]
    .set_index("model")[["rmse", "mae"]]
)

training_summary = {
    "best_epoch": int(best_epoch),
    "epochs_run": int(len(training_history_df)),
    "training_seconds": round(float(training_seconds), 2),
    "best_train_rmse": round(bnn_train_metrics["rmse"], 4),
    "best_train_mae": round(bnn_train_metrics["mae"], 4),
    "best_validation_rmse": round(bnn_val_metrics["rmse"], 4),
    "best_validation_mae": round(bnn_val_metrics["mae"], 4),
    "validation_mf_rmse": float(validation_baselines.loc["mf_score", "rmse"]),
    "validation_hybrid_rmse": float(validation_baselines.loc["hybrid_score", "rmse"]),
    "bnn_beats_validation_mf_rmse": bool(
        bnn_val_metrics["rmse"] < validation_baselines.loc["mf_score", "rmse"]
    ),
    "bnn_beats_validation_hybrid_rmse": bool(
        bnn_val_metrics["rmse"] < validation_baselines.loc["hybrid_score", "rmse"]
    ),
}

print("\nTraining summary:")
display(training_summary)

print("\nLast 10 epochs:")
display(training_history_df.tail(10).round(4))

print("\nValidation baseline comparison:")
display(validation_baselines)

Epoch 001 | train RMSE 0.7678 | val RMSE 0.7537 | val MAE 0.4642
Epoch 002 | train RMSE 0.7548 | val RMSE 0.7479 | val MAE 0.4699
Epoch 003 | train RMSE 0.7455 | val RMSE 0.7419 | val MAE 0.4504
Epoch 004 | train RMSE 0.7395 | val RMSE 0.7383 | val MAE 0.4459
Epoch 005 | train RMSE 0.7326 | val RMSE 0.7366 | val MAE 0.4452
Epoch 010 | train RMSE 0.7137 | val RMSE 0.7391 | val MAE 0.4336
Epoch 012 | train RMSE 0.7032 | val RMSE 0.7350 | val MAE 0.4379
Epoch 015 | train RMSE 0.6916 | val RMSE 0.7337 | val MAE 0.4306
Epoch 020 | train RMSE 0.6706 | val RMSE 0.7457 | val MAE 0.4202
Epoch 030 | train RMSE 0.6358 | val RMSE 0.7474 | val MAE 0.4326
Epoch 040 | train RMSE 0.6156 | val RMSE 0.7573 | val MAE 0.4215
Early stopping at epoch 45. Best validation RMSE: 0.7337 at epoch 15.

Training summary:

{'best_epoch': 15,
 'epochs_run': 45,
 'training_seconds': 33.15,
 'best_train_rmse': 0.6916,
 'best_train_mae': 0.4208,
 'best_validation_rmse': 0.7337,
 'best_validation_mae': 0.4306,
 'validation_mf_rmse': 0.7578,
 'validation_hybrid_rmse': 0.7774,
 'bnn_beats_validation_mf_rmse': True,
 'bnn_beats_validation_hybrid_rmse': True}

Last 10 epochs:

    epoch  train_loss  train_rmse  train_mae  val_rmse  val_mae  val_pred_mean
35     36      0.4284      0.6320     0.3675    0.7519   0.4165         4.5804
36     37      0.4309      0.6258     0.3796    0.7502   0.4318         4.5431
37     38      0.4277      0.6178     0.3585    0.7586   0.4167         4.5626
38     39      0.4264      0.6146     0.3650    0.7545   0.4251         4.5200
39     40      0.4245      0.6156     0.3638    0.7573   0.4215         4.5406
40     41      0.4152      0.6157     0.3697    0.7583   0.4317         4.5482
41     42      0.4192      0.6096     0.3698    0.7597   0.4351         4.5277
42     43      0.4174      0.6094     0.3657    0.7528   0.4264         4.5422
43     44      0.4161      0.6002     0.3581    0.7570   0.4256         4.5302
44     45      0.4132      0.6112     0.3643    0.7586   0.4270         4.5610

Validation baseline comparison:

                        rmse     mae
model
mf_score              0.7578  0.4734
content_rating_score  0.9773  0.7976
hybrid_score          0.7774  0.5607

- The first MC-dropout BNN training run is successful.
- Best validation performance happened early, at epoch `7`, so the later epochs were overfitting.
- The BNN validation RMSE is `0.7824`, which beats:
  - MF validation RMSE: `0.7970`
  - hybrid validation RMSE: `0.8012`
- This is the first evidence that combining MF, content, metadata, and embedding features with a learned nonlinear model improves rating prediction.
- Validation MAE is `0.5063`, which is close to MF MAE `0.5043`; so the BNN improves RMSE more than MAE.
- Training RMSE `0.7273` vs validation RMSE `0.7824` shows mild overfitting, but early stopping controlled it.
- Next, we should use MC dropout at inference time to produce both predicted rating and uncertainty, then check whether higher uncertainty corresponds to higher prediction error.

# Step 10: MC-Dropout Uncertainty Evaluation

In [11]:
MC_SAMPLES = 100
MC_BATCH_SIZE = 512

def predict_mc_dropout(model, X_array, n_samples=100, batch_size=512):
    """
    Run repeated stochastic forward passes with dropout active.
    Returns prediction samples, mean prediction, std uncertainty, and interval bounds.
    """
    model.train()  # intentionally keep dropout active for MC sampling

    sample_predictions = []

    with torch.no_grad():
        for sample_idx in range(n_samples):
            batch_predictions = []

            for start in range(0, len(X_array), batch_size):
                batch = torch.tensor(
                    X_array[start:start + batch_size],
                    dtype=torch.float32,
                    device=DEVICE,
                )

                preds = model(batch).detach().cpu().numpy().ravel()
                batch_predictions.append(preds)

            sample_predictions.append(np.concatenate(batch_predictions))

    model.eval()

    samples = np.vstack(sample_predictions)

    prediction_mean = samples.mean(axis=0)
    prediction_std = samples.std(axis=0)
    prediction_lower_95 = np.percentile(samples, 2.5, axis=0)
    prediction_upper_95 = np.percentile(samples, 97.5, axis=0)

    return {
        "samples": samples,
        "mean": prediction_mean,
        "std": prediction_std,
        "lower_95": prediction_lower_95,
        "upper_95": prediction_upper_95,
    }

def safe_correlation(a, b):
    a = np.asarray(a)
    b = np.asarray(b)

    if np.std(a) == 0 or np.std(b) == 0:
        return np.nan

    return float(np.corrcoef(a, b)[0, 1])

def build_uncertainty_eval_df(split_df, y_true, mc_result, split_name):
    out = split_df[
        [
            "author_id",
            "product_id",
            "product_name",
            "brand_name",
            "secondary_category",
            "tertiary_category",
            "true_rating",
            "mf_score",
            "content_rating_score",
            "hybrid_score",
        ]
    ].copy()

    out["split"] = split_name
    out["bnn_mean_score"] = np.clip(mc_result["mean"], 1, 5)
    out["bnn_uncertainty"] = mc_result["std"]
    out["bnn_lower_95"] = np.clip(mc_result["lower_95"], 1, 5)
    out["bnn_upper_95"] = np.clip(mc_result["upper_95"], 1, 5)
    out["bnn_abs_error"] = np.abs(out["true_rating"] - out["bnn_mean_score"])
    out["mf_abs_error"] = np.abs(out["true_rating"] - out["mf_score"])
    out["hybrid_abs_error"] = np.abs(out["true_rating"] - out["hybrid_score"])
    out["interval_contains_true_rating"] = (
        (out["true_rating"] >= out["bnn_lower_95"])
        & (out["true_rating"] <= out["bnn_upper_95"])
    )

    # Rank before qcut to avoid duplicate-edge failures if uncertainties repeat.
    out["uncertainty_bucket"] = pd.qcut(
        out["bnn_uncertainty"].rank(method="first"),
        q=3,
        labels=["low", "medium", "high"],
    )

    return out

print("Running MC-dropout inference on validation split...")
val_mc = predict_mc_dropout(
    model,
    X_val,
    n_samples=MC_SAMPLES,
    batch_size=MC_BATCH_SIZE,
)

print("Running MC-dropout inference on test split...")
test_mc = predict_mc_dropout(
    model,
    X_test,
    n_samples=MC_SAMPLES,
    batch_size=MC_BATCH_SIZE,
)

val_uncertainty_df = build_uncertainty_eval_df(
    val_df_bnn,
    y_val,
    val_mc,
    split_name="validation",
)

test_uncertainty_df = build_uncertainty_eval_df(
    test_df_bnn,
    y_test,
    test_mc,
    split_name="test",
)

mc_metric_rows = []

for split_name, split_df, uncertainty_df in [
    ("validation", val_df_bnn, val_uncertainty_df),
    ("test", test_df_bnn, test_uncertainty_df),
]:
    for model_name, score_column in [
        ("mf_score", "mf_score"),
        ("content_rating_score", "content_rating_score"),
        ("hybrid_score", "hybrid_score"),
        ("bnn_mc_mean", "bnn_mean_score"),
    ]:
        mc_metric_rows.append(
            {
                "split": split_name,
                "model": model_name,
                "rmse": rmse_score(
                    uncertainty_df["true_rating"],
                    uncertainty_df[score_column],
                ),
                "mae": float(
                    mean_absolute_error(
                        uncertainty_df["true_rating"],
                        uncertainty_df[score_column],
                    )
                ),
                "pred_mean": float(uncertainty_df[score_column].mean()),
            }
        )

mc_metrics_table = pd.DataFrame(mc_metric_rows).round(4)

uncertainty_summary_rows = []

for split_name, uncertainty_df in [
    ("validation", val_uncertainty_df),
    ("test", test_uncertainty_df),
]:
    uncertainty_summary_rows.append(
        {
            "split": split_name,
            "rows": len(uncertainty_df),
            "mean_uncertainty": uncertainty_df["bnn_uncertainty"].mean(),
            "median_uncertainty": uncertainty_df["bnn_uncertainty"].median(),
            "max_uncertainty": uncertainty_df["bnn_uncertainty"].max(),
            "mean_abs_error": uncertainty_df["bnn_abs_error"].mean(),
            "uncertainty_abs_error_corr": safe_correlation(
                uncertainty_df["bnn_uncertainty"],
                uncertainty_df["bnn_abs_error"],
            ),
            "interval_95_coverage": uncertainty_df["interval_contains_true_rating"].mean(),
        }
    )

uncertainty_summary = pd.DataFrame(uncertainty_summary_rows).round(4)

bucket_summary = (
    pd.concat([val_uncertainty_df, test_uncertainty_df], ignore_index=True)
    .groupby(["split", "uncertainty_bucket"], observed=True)
    .agg(
        rows=("bnn_abs_error", "size"),
        mean_uncertainty=("bnn_uncertainty", "mean"),
        mean_abs_error=("bnn_abs_error", "mean"),
        rmse=("bnn_abs_error", lambda values: float(np.sqrt(np.mean(values ** 2)))),
        interval_95_coverage=("interval_contains_true_rating", "mean"),
    )
    .reset_index()
    .round(4)
)

test_decision_report = {
    "test_bnn_rmse": float(
        mc_metrics_table[
            (mc_metrics_table["split"] == "test")
            & (mc_metrics_table["model"] == "bnn_mc_mean")
        ]["rmse"].iloc[0]
    ),
    "test_mf_rmse": float(
        mc_metrics_table[
            (mc_metrics_table["split"] == "test")
            & (mc_metrics_table["model"] == "mf_score")
        ]["rmse"].iloc[0]
    ),
    "test_hybrid_rmse": float(
        mc_metrics_table[
            (mc_metrics_table["split"] == "test")
            & (mc_metrics_table["model"] == "hybrid_score")
        ]["rmse"].iloc[0]
    ),
}

test_decision_report["bnn_beats_test_mf_rmse"] = (
    test_decision_report["test_bnn_rmse"]
    < test_decision_report["test_mf_rmse"]
)

test_decision_report["bnn_beats_test_hybrid_rmse"] = (
    test_decision_report["test_bnn_rmse"]
    < test_decision_report["test_hybrid_rmse"]
)

print("MC-dropout rating metrics:")
display(mc_metrics_table)

print("\nUncertainty summary:")
display(uncertainty_summary)

print("\nUncertainty bucket summary:")
display(bucket_summary)

print("\nTest decision report:")
display(test_decision_report)

print("\nMost uncertain test predictions:")
display(
    test_uncertainty_df.sort_values("bnn_uncertainty", ascending=False)
    [
        [
            "author_id",
            "product_id",
            "product_name",
            "brand_name",
            "true_rating",
            "bnn_mean_score",
            "bnn_uncertainty",
            "bnn_abs_error",
            "mf_score",
            "mf_abs_error",
        ]
    ]
    .head(10)
    .round(4)
)

Running MC-dropout inference on validation split...

Running MC-dropout inference on test split...
MC-dropout rating metrics:

        split                 model    rmse     mae  pred_mean
0  validation              mf_score  0.7578  0.4734     4.4942
1  validation  content_rating_score  0.9773  0.7976     4.2386
2  validation          hybrid_score  0.7774  0.5607     4.4175
3  validation           bnn_mc_mean  0.7330  0.4356     4.5220
4        test              mf_score  0.7807  0.4912     4.4788
5        test  content_rating_score  1.0069  0.8139     4.2375
6        test          hybrid_score  0.8040  0.5770     4.4064
7        test           bnn_mc_mean  0.7793  0.4687     4.5007

Uncertainty summary:

,split,rows,mean_uncertainty,median_uncertainty,max_uncertainty,mean_abs_error,uncertainty_abs_error_corr,interval_95_coverage
0,validation,5519,0.0941,0.0841,0.5278,0.4356,0.5280,0.0873
1,test,27822,0.0984,0.0917,0.6293,0.4687,0.4994,0.0901

Uncertainty bucket summary:

,split,uncertainty_bucket,rows,mean_uncertainty,mean_abs_error,rmse,interval_95_coverage
0,test,low,9274,0.0286,0.1003,0.2745,0.0000
1,test,medium,9274,0.0901,0.4706,0.7275,0.0278
2,test,high,9274,0.1765,0.8352,1.1034,0.2424
3,validation,low,1840,0.0273,0.0860,0.2415,0.0000
4,validation,medium,1839,0.0849,0.4194,0.6590,0.0196
5,validation,high,1840,0.1700,0.8015,1.0578,0.2424

Test decision report:

{'test_bnn_rmse': 0.7793,
 'test_mf_rmse': 0.7807,
 'test_hybrid_rmse': 0.804,
 'bnn_beats_test_mf_rmse': True,
 'bnn_beats_test_hybrid_rmse': True}

Most uncertain test predictions:

,author_id,product_id,product_name,brand_name,true_rating,bnn_mean_score,bnn_uncertainty,bnn_abs_error,mf_score,mf_abs_error
6623,1696370280,P444222,Luxury Beauty Serum Calming Treatment,Saint Jane Beauty,3.0,3.8974,0.6293,0.8974,4.2287,1.2287
6614,1696370280,P450210,Vitamin Nectar Glow Juice Antioxidant Face Serum,fresh,5.0,2.7570,0.6235,2.2430,3.6749,1.3251
6638,1696370280,P500471,Brume de Beauté Beauty Mist,Gucci,5.0,3.7709,0.6159,1.2291,4.3624,0.6376
10513,22658221971,P474826,Advanced Retinol + Ferulic Texture Renewal Serum,Dr. Dennis Gross Skincare,5.0,3.3847,0.5999,1.6153,4.2251,0.7749
26028,8714225928,P397890,Original Skin Retexturizing Mask with Rose Clay,Origins,5.0,3.1373,0.5960,1.8627,3.6349,1.3651
14548,2760276,P453713,Collagen POP + Vitamin C Dissolvable Tablets,HUM Nutrition,1.0,3.2245,0.5859,2.2245,3.8043,2.8043
6646,1696370280,P416139,Mini C.E.O. Vitamin C Brightening Rich Hydrati...,Sunday Riley,3.0,3.0744,0.5833,0.0744,3.6896,0.6896
6849,1737922340,P469524,RESIST Super-Light Daily Wrinkle Defense SPF 30,Paula's Choice,5.0,3.7990,0.5713,1.2010,3.2881,1.7119
3644,1288462295,P470533,Blending Brush,Isle of Paradise,5.0,3.8528,0.5712,1.1472,3.7843,1.2157
3176,1247121950,P442989,Youth or Dare Multi-Acid & C-Serum,tarte,5.0,2.8368,0.5588,2.1632,2.2662,2.7338

- The BNN now beats the strongest test baseline on RMSE:
  - BNN test RMSE: `0.7636`
  - MF test RMSE: `0.7786`
  - hybrid test RMSE: `0.7922`
- This is a real improvement for final rating prediction, especially because MF was already a strong baseline.
- BNN test MAE is `0.4956`, slightly worse than MF MAE `0.4888`, so the BNN improves larger-error behavior more than average absolute error.
- The uncertainty signal is useful for ranking confidence:
  - low uncertainty test MAE: `0.1649`
  - medium uncertainty test MAE: `0.4669`
  - high uncertainty test MAE: `0.8548`
- This is exactly the pattern we want: higher uncertainty corresponds to higher error.
- However, the 95% interval coverage is far too low, especially in low/medium buckets, so raw MC-dropout intervals are under-calibrated.
- Next, we should calibrate uncertainty using the validation split before exporting final BNN predictions.

# Step 11: Calibrate Uncertainty Intervals

In [12]:

EPSILON = 1e-8
TARGET_COVERAGE = 0.95

# Fit calibration only on validation data.
val_standardized_abs_error = (
    val_uncertainty_df["bnn_abs_error"]
    / (val_uncertainty_df["bnn_uncertainty"] + EPSILON)
)

uncertainty_interval_multiplier = float(
    np.quantile(val_standardized_abs_error, TARGET_COVERAGE)
)

# Use validation uncertainty quantiles for stable bucket thresholds.
low_threshold = float(val_uncertainty_df["bnn_uncertainty"].quantile(1 / 3))
high_threshold = float(val_uncertainty_df["bnn_uncertainty"].quantile(2 / 3))

def apply_uncertainty_calibration(df):
    out = df.copy()

    out["calibrated_interval_half_width"] = (
        uncertainty_interval_multiplier * out["bnn_uncertainty"]
    )

    out["bnn_calibrated_lower_95"] = (
        out["bnn_mean_score"] - out["calibrated_interval_half_width"]
    ).clip(1, 5)

    out["bnn_calibrated_upper_95"] = (
        out["bnn_mean_score"] + out["calibrated_interval_half_width"]
    ).clip(1, 5)

    out["calibrated_interval_contains_true_rating"] = (
        (out["true_rating"] >= out["bnn_calibrated_lower_95"])
        & (out["true_rating"] <= out["bnn_calibrated_upper_95"])
    )

    out["confidence_bucket"] = np.select(
        [
            out["bnn_uncertainty"] <= low_threshold,
            out["bnn_uncertainty"] <= high_threshold,
        ],
        [
            "high_confidence",
            "medium_confidence",
        ],
        default="low_confidence",
    )

    # Risk-adjusted score is useful later for recommendations:
    # high predicted rating is rewarded, high uncertainty is penalized.
    out["risk_adjusted_score"] = (
        out["bnn_mean_score"] - 0.5 * out["bnn_uncertainty"]
    ).clip(1, 5)

    return out

val_calibrated_df = apply_uncertainty_calibration(val_uncertainty_df)
test_calibrated_df = apply_uncertainty_calibration(test_uncertainty_df)

calibration_metric_rows = []

for split_name, calibrated_df in [
    ("validation", val_calibrated_df),
    ("test", test_calibrated_df),
]:
    calibration_metric_rows.append(
        {
            "split": split_name,
            "rows": len(calibrated_df),
            "mean_uncertainty": calibrated_df["bnn_uncertainty"].mean(),
            "raw_interval_coverage": calibrated_df["interval_contains_true_rating"].mean(),
            "calibrated_interval_coverage": calibrated_df[
                "calibrated_interval_contains_true_rating"
            ].mean(),
            "mean_raw_interval_width": (
                calibrated_df["bnn_upper_95"] - calibrated_df["bnn_lower_95"]
            ).mean(),
            "mean_calibrated_interval_width": (
                calibrated_df["bnn_calibrated_upper_95"]
                - calibrated_df["bnn_calibrated_lower_95"]
            ).mean(),
            "uncertainty_abs_error_corr": safe_correlation(
                calibrated_df["bnn_uncertainty"],
                calibrated_df["bnn_abs_error"],
            ),
        }
    )

calibration_metrics = pd.DataFrame(calibration_metric_rows).round(4)

confidence_bucket_summary = (
    pd.concat([val_calibrated_df, test_calibrated_df], ignore_index=True)
    .groupby(["split", "confidence_bucket"], observed=True)
    .agg(
        rows=("bnn_abs_error", "size"),
        mean_predicted_score=("bnn_mean_score", "mean"),
        mean_risk_adjusted_score=("risk_adjusted_score", "mean"),
        mean_uncertainty=("bnn_uncertainty", "mean"),
        mean_abs_error=("bnn_abs_error", "mean"),
        rmse=("bnn_abs_error", lambda values: float(np.sqrt(np.mean(values ** 2)))),
        calibrated_interval_coverage=(
            "calibrated_interval_contains_true_rating",
            "mean",
        ),
    )
    .reset_index()
    .sort_values(["split", "mean_uncertainty"])
    .round(4)
)

calibration_report = {
    "target_coverage": TARGET_COVERAGE,
    "uncertainty_interval_multiplier": uncertainty_interval_multiplier,
    "validation_low_uncertainty_threshold": low_threshold,
    "validation_high_uncertainty_threshold": high_threshold,
}

print("Calibration report:")
display(calibration_report)

print("\nCalibration metrics:")
display(calibration_metrics)

print("\nConfidence bucket summary:")
display(confidence_bucket_summary)

print("\nPreview calibrated test predictions:")
display(
    test_calibrated_df[
        [
            "author_id",
            "product_id",
            "product_name",
            "true_rating",
            "bnn_mean_score",
            "risk_adjusted_score",
            "bnn_uncertainty",
            "confidence_bucket",
            "bnn_calibrated_lower_95",
            "bnn_calibrated_upper_95",
            "calibrated_interval_contains_true_rating",
        ]
    ]
    .sort_values("bnn_uncertainty", ascending=False)
    .head(10)
    .round(4)
)

Calibration report:

{'target_coverage': 0.95,
 'uncertainty_interval_multiplier': 13.861844327962183,
 'validation_low_uncertainty_threshold': 0.04630618542432785,
 'validation_high_uncertainty_threshold': 0.12395479778448741}

Calibration metrics:

,split,rows,mean_uncertainty,raw_interval_coverage,calibrated_interval_coverage,mean_raw_interval_width,mean_calibrated_interval_width,uncertainty_abs_error_corr
0,validation,5519,0.0941,0.0873,0.9500,0.3518,1.6783,0.5280
1,test,27822,0.0984,0.0901,0.9444,0.3679,1.7442,0.4994

Confidence bucket summary:

,split,confidence_bucket,rows,mean_predicted_score,mean_risk_adjusted_score,mean_uncertainty,mean_abs_error,rmse,calibrated_interval_coverage
0,test,high_confidence,8872,4.9513,4.9374,0.0278,0.0964,0.2689,0.9558
2,test,medium_confidence,9046,4.6773,4.6344,0.0857,0.4444,0.7044,0.9256
1,test,low_confidence,9904,3.9359,3.8493,0.1733,0.8245,1.0900,0.9514
3,validation,high_confidence,1840,4.9521,4.9384,0.0273,0.0860,0.2415,0.9641
5,validation,medium_confidence,1839,4.6883,4.6458,0.0849,0.4194,0.6590,0.9331
4,validation,low_confidence,1840,3.9256,3.8405,0.1700,0.8015,1.0578,0.9527

Preview calibrated test predictions:

,author_id,product_id,product_name,true_rating,bnn_mean_score,risk_adjusted_score,bnn_uncertainty,confidence_bucket,bnn_calibrated_lower_95,bnn_calibrated_upper_95,calibrated_interval_contains_true_rating
6623,1696370280,P444222,Luxury Beauty Serum Calming Treatment,3.0,3.8974,3.5827,0.6293,low_confidence,1.0,5.0,True
6614,1696370280,P450210,Vitamin Nectar Glow Juice Antioxidant Face Serum,5.0,2.7570,2.4453,0.6235,low_confidence,1.0,5.0,True
6638,1696370280,P500471,Brume de Beauté Beauty Mist,5.0,3.7709,3.4630,0.6159,low_confidence,1.0,5.0,True
10513,22658221971,P474826,Advanced Retinol + Ferulic Texture Renewal Serum,5.0,3.3847,3.0847,0.5999,low_confidence,1.0,5.0,True
26028,8714225928,P397890,Original Skin Retexturizing Mask with Rose Clay,5.0,3.1373,2.8393,0.5960,low_confidence,1.0,5.0,True
14548,2760276,P453713,Collagen POP + Vitamin C Dissolvable Tablets,1.0,3.2245,2.9315,0.5859,low_confidence,1.0,5.0,True
6646,1696370280,P416139,Mini C.E.O. Vitamin C Brightening Rich Hydrati...,3.0,3.0744,2.7827,0.5833,low_confidence,1.0,5.0,True
6849,1737922340,P469524,RESIST Super-Light Daily Wrinkle Defense SPF 30,5.0,3.7990,3.5134,0.5713,low_confidence,1.0,5.0,True
3644,1288462295,P470533,Blending Brush,5.0,3.8528,3.5672,0.5712,low_confidence,1.0,5.0,True
3176,1247121950,P442989,Youth or Dare Multi-Acid & C-Serum,5.0,2.8368,2.5574,0.5588,low_confidence,1.0,5.0,True

- Uncertainty calibration worked very well on the held-out test split.
- Raw MC-dropout intervals were too narrow:
  - validation raw coverage: `0.0575`
  - test raw coverage: `0.0478`
- After validation-based calibration, interval coverage became close to the intended 95%:
  - validation calibrated coverage: `0.9500`
  - test calibrated coverage: `0.9465`
- The uncertainty signal remains meaningful after calibration:
  - high-confidence test rows have low MAE: `0.1768`
  - medium-confidence rows have higher MAE: `0.5041`
  - low-confidence rows have highest MAE: `0.8575`
- The uncertainty-error correlation is positive on test: `0.3949`, which supports the claim that uncertainty is informative.
- Some low-confidence intervals become very wide, often `[1, 5]`; this is acceptable for honest uncertainty, but recommendations should prefer high/medium-confidence products.
- Next, we should export the trained model, preprocessing objects, predictions, metrics, and version log so this run becomes a reusable Step 5 artifact.

# Step 12: Export Validation

In [13]:
# Step 12: Export Validation Retry

import joblib
import json
import torch

STEP5_DIR = RUN_DIR / "step5_bnn"
STEP5_DIR.mkdir(parents=True, exist_ok=True)

RESULTS_LOG_CSV = VERSION_ROOT / "results_log.csv"
RESULTS_LOG_MD = VERSION_ROOT / "results_log.md"

def to_jsonable(value):
    if isinstance(value, dict):
        return {str(k): to_jsonable(v) for k, v in value.items()}
    if isinstance(value, list):
        return [to_jsonable(v) for v in value]
    if isinstance(value, tuple):
        return [to_jsonable(v) for v in value]
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, pd.DataFrame):
        return value.to_dict(orient="records")
    if isinstance(value, pd.Series):
        return value.to_dict()
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, (np.bool_,)):
        return bool(value)
    return value

def write_json(path, payload):
    with open(path, "w") as f:
        json.dump(to_jsonable(payload), f, indent=2)

def dataframe_to_markdown_no_tabulate(df):
    """Small dependency-free markdown table writer."""
    if df.empty:
        return "_No rows._"

    display_df = df.copy()

    for col in display_df.columns:
        display_df[col] = display_df[col].map(
            lambda value: f"{value:.4f}" if isinstance(value, float) else str(value)
        )

    headers = list(display_df.columns)
    rows = display_df.values.tolist()

    lines = []
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")

    for row in rows:
        escaped_row = [
            str(value).replace("|", "\\|")
            for value in row
        ]
        lines.append("| " + " | ".join(escaped_row) + " |")

    return "\n".join(lines)

feature_schema = {
    "target_column": TARGET_COLUMN,
    "id_columns": ID_COLUMNS,
    "numeric_features": numeric_features,
    "categorical_features": categorical_features,
    "feature_columns": feature_columns,
    "encoded_feature_count": int(X_train.shape[1]),
    "encoded_feature_names": encoded_feature_names.tolist(),
    "top_brand_count": int(TOP_BRAND_COUNT),
    "top_brands": list(map(str, top_brands)),
    "embedding_components": int(EMBEDDING_COMPONENTS),
    "reduced_embedding_columns": reduced_embedding_columns,
}

model_config = {
    "model_type": "MC Dropout Bayesian Neural Network",
    "input_dim": int(input_dim),
    "hidden_1": int(HIDDEN_1),
    "hidden_2": int(HIDDEN_2),
    "dropout_rate": float(DROPOUT_RATE),
    "batch_size": int(BATCH_SIZE),
    "learning_rate": float(LEARNING_RATE),
    "weight_decay": float(WEIGHT_DECAY),
    "max_epochs": int(MAX_EPOCHS),
    "early_stopping_patience": int(EARLY_STOPPING_PATIENCE),
    "best_epoch": int(best_epoch),
    "mc_samples": int(MC_SAMPLES),
    "device_used": str(DEVICE),
}

all_metrics = {
    "run_metadata": run_metadata,
    "model_report": model_report,
    "embedding_join_report": embedding_join_report,
    "split_report": split_report,
    "overlap_report": overlap_report,
    "training_summary": training_summary,
    "test_decision_report": test_decision_report,
    "calibration_report": calibration_report,
    "split_baseline_metrics": split_baseline_metrics,
    "mc_metrics_table": mc_metrics_table,
    "calibration_metrics": calibration_metrics,
    "confidence_bucket_summary": confidence_bucket_summary,
}

modeling_with_embeddings_df.to_csv(
    STEP4_DIR / "model_features.csv",
    index=False,
)

category_cardinality.to_csv(
    STEP4_DIR / "category_cardinality.csv",
    index=False,
)

pca_summary.to_csv(
    STEP4_DIR / "embedding_pca_summary.csv",
    index=False,
)

write_json(
    STEP4_DIR / "feature_schema.json",
    feature_schema,
)

write_json(
    STEP4_DIR / "run_metadata.json",
    run_metadata,
)

joblib.dump(
    pca,
    STEP4_DIR / "embedding_pca.joblib",
)

torch.save(
    {
        "model_state_dict": {
            key: value.detach().cpu()
            for key, value in model.state_dict().items()
        },
        "model_config": model_config,
        "feature_schema": feature_schema,
    },
    STEP5_DIR / "mc_dropout_bnn_model.pt",
)

joblib.dump(
    preprocessor,
    STEP5_DIR / "preprocessor.joblib",
)

training_history_df.to_csv(
    STEP5_DIR / "training_history.csv",
    index=False,
)

split_baseline_metrics.to_csv(
    STEP5_DIR / "split_baseline_metrics.csv",
    index=False,
)

mc_metrics_table.to_csv(
    STEP5_DIR / "mc_dropout_metrics.csv",
    index=False,
)

calibration_metrics.to_csv(
    STEP5_DIR / "calibration_metrics.csv",
    index=False,
)

confidence_bucket_summary.to_csv(
    STEP5_DIR / "confidence_bucket_summary.csv",
    index=False,
)

val_calibrated_df.to_csv(
    STEP5_DIR / "validation_predictions_calibrated.csv",
    index=False,
)

test_calibrated_df.to_csv(
    STEP5_DIR / "test_predictions_calibrated.csv",
    index=False,
)

write_json(
    STEP5_DIR / "model_config.json",
    model_config,
)

write_json(
    STEP5_DIR / "all_metrics.json",
    all_metrics,
)

test_bnn_row = mc_metrics_table[
    (mc_metrics_table["split"] == "test")
    & (mc_metrics_table["model"] == "bnn_mc_mean")
].iloc[0]

test_mf_row = mc_metrics_table[
    (mc_metrics_table["split"] == "test")
    & (mc_metrics_table["model"] == "mf_score")
].iloc[0]

test_hybrid_row = mc_metrics_table[
    (mc_metrics_table["split"] == "test")
    & (mc_metrics_table["model"] == "hybrid_score")
].iloc[0]

test_calibration_row = calibration_metrics[
    calibration_metrics["split"] == "test"
].iloc[0]

log_row = {
    "run_id": RUN_ID,
    "created_at": run_metadata["created_at"],
    "model_type": model_config["model_type"],
    "best_epoch": model_config["best_epoch"],
    "mc_samples": model_config["mc_samples"],
    "dropout_rate": model_config["dropout_rate"],
    "test_mf_rmse": test_mf_row["rmse"],
    "test_hybrid_rmse": test_hybrid_row["rmse"],
    "test_bnn_rmse": test_bnn_row["rmse"],
    "test_mf_mae": test_mf_row["mae"],
    "test_hybrid_mae": test_hybrid_row["mae"],
    "test_bnn_mae": test_bnn_row["mae"],
    "bnn_beats_test_mf_rmse": test_decision_report["bnn_beats_test_mf_rmse"],
    "bnn_beats_test_hybrid_rmse": test_decision_report["bnn_beats_test_hybrid_rmse"],
    "test_uncertainty_abs_error_corr": test_calibration_row["uncertainty_abs_error_corr"],
    "test_calibrated_interval_coverage": test_calibration_row["calibrated_interval_coverage"],
}

if RESULTS_LOG_CSV.exists():
    results_log_df = pd.read_csv(RESULTS_LOG_CSV)
    results_log_df = results_log_df[results_log_df["run_id"] != RUN_ID]
    results_log_df = pd.concat(
        [results_log_df, pd.DataFrame([log_row])],
        ignore_index=True,
    )
else:
    results_log_df = pd.DataFrame([log_row])

results_log_df.to_csv(RESULTS_LOG_CSV, index=False)

best_rmse_so_far = results_log_df["test_bnn_rmse"].min()
best_run_so_far = results_log_df.loc[
    results_log_df["test_bnn_rmse"].idxmin(),
    "run_id",
]

with open(RESULTS_LOG_MD, "w") as f:
    f.write("# MC-BNN Version Results Log\n\n")
    f.write(f"Best run so far by test BNN RMSE: `{best_run_so_far}` ")
    f.write(f"with RMSE `{best_rmse_so_far:.4f}`.\n\n")
    f.write(dataframe_to_markdown_no_tabulate(results_log_df.sort_values("run_id")))
    f.write("\n")

expected_exports = [
    STEP4_DIR / "model_features.csv",
    STEP4_DIR / "feature_schema.json",
    STEP4_DIR / "run_metadata.json",
    STEP4_DIR / "category_cardinality.csv",
    STEP4_DIR / "embedding_pca_summary.csv",
    STEP4_DIR / "embedding_pca.joblib",
    STEP5_DIR / "mc_dropout_bnn_model.pt",
    STEP5_DIR / "preprocessor.joblib",
    STEP5_DIR / "training_history.csv",
    STEP5_DIR / "split_baseline_metrics.csv",
    STEP5_DIR / "mc_dropout_metrics.csv",
    STEP5_DIR / "calibration_metrics.csv",
    STEP5_DIR / "confidence_bucket_summary.csv",
    STEP5_DIR / "validation_predictions_calibrated.csv",
    STEP5_DIR / "test_predictions_calibrated.csv",
    STEP5_DIR / "model_config.json",
    STEP5_DIR / "all_metrics.json",
    RESULTS_LOG_CSV,
    RESULTS_LOG_MD,
]

export_validation = pd.DataFrame(
    {
        "path": [str(path) for path in expected_exports],
        "exists": [path.exists() for path in expected_exports],
        "size_bytes": [
            path.stat().st_size if path.exists() else 0
            for path in expected_exports
        ],
    }
)

export_report = {
    "run_id": RUN_ID,
    "run_dir": str(RUN_DIR),
    "step4_dir": str(STEP4_DIR),
    "step5_dir": str(STEP5_DIR),
    "expected_export_count": int(len(expected_exports)),
    "successful_export_count": int(export_validation["exists"].sum()),
    "all_exports_exist": bool(export_validation["exists"].all()),
    "best_run_so_far": str(best_run_so_far),
    "best_rmse_so_far": float(best_rmse_so_far),
}

print("Export report:")
display(export_report)

print("\nExport validation:")
display(export_validation)

print("\nUpdated results log:")
display(results_log_df.sort_values("run_id"))

Export report:

{'run_id': 'v002',
 'run_dir': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002',
 'step4_dir': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002/step4_features',
 'step5_dir': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002/step5_bnn',
 'expected_export_count': 19,
 'successful_export_count': 19,
 'all_exports_exist': True,
 'best_run_so_far': 'v001',
 'best_rmse_so_far': 0.7636}

Export validation:

                                                 path  exists  size_bytes
0   /Users/veerr_89/Work/projects/up-skin/artifact...    True    75020314
1   /Users/veerr_89/Work/projects/up-skin/artifact...    True       10893
2   /Users/veerr_89/Work/projects/up-skin/artifact...    True         283
3   /Users/veerr_89/Work/projects/up-skin/artifact...    True         160
4   /Users/veerr_89/Work/projects/up-skin/artifact...    True        1328
5   /Users/veerr_89/Work/projects/up-skin/artifact...    True       51994
6   /Users/veerr_89/Work/projects/up-skin/artifact...    True      116529
7   /Users/veerr_89/Work/projects/up-skin/artifact...    True       11080
8   /Users/veerr_89/Work/projects/up-skin/artifact...    True        5316
9   /Users/veerr_89/Work/projects/up-skin/artifact...    True         543
10  /Users/veerr_89/Work/projects/up-skin/artifact...    True         369
11  /Users/veerr_89/Work/projects/up-skin/artifact...    True         269
12  /Users/veerr_89/Work/projects/up-skin/artifact...    True         563
13  /Users/veerr_89/Work/projects/up-skin/artifact...    True     1815182
14  /Users/veerr_89/Work/projects/up-skin/artifact...    True     8987235
15  /Users/veerr_89/Work/projects/up-skin/artifact...    True         328
16  /Users/veerr_89/Work/projects/up-skin/artifact...    True        8298
17  /Users/veerr_89/Work/projects/up-skin/artifact...    True         536
18  /Users/veerr_89/Work/projects/up-skin/artifact...    True         836

Updated results log:

,run_id,created_at,model_type,best_epoch,mc_samples,dropout_rate,test_mf_rmse,test_hybrid_rmse,test_bnn_rmse,test_mf_mae,test_hybrid_mae,test_bnn_mae,bnn_beats_test_mf_rmse,bnn_beats_test_hybrid_rmse,test_uncertainty_abs_error_corr,test_calibrated_interval_coverage
0,v001,2026-04-27T15:46:49,MC Dropout Bayesian Neural Network,7,100,0.2,0.7786,0.7922,0.7636,0.4888,0.5726,0.4956,True,True,0.3949,0.9465
1,v002,2026-05-05T23:38:36,MC Dropout Bayesian Neural Network,15,100,0.2,0.7807,0.8040,0.7793,0.4912,0.5770,0.4687,True,True,0.4994,0.9444

- Export validation passed: all `19` expected artifacts were written successfully.
- Run `v001` is now the current best run, with test BNN RMSE `0.7636`.
- The exported artifacts include:
  - Step 4 feature table and schema
  - PCA reducer
  - trained MC-dropout BNN checkpoint
  - preprocessing pipeline
  - calibrated validation/test predictions
  - metrics and version logs
- The results log confirms the BNN beats both key test baselines on RMSE:
  - MF RMSE: `0.7786`
  - hybrid RMSE: `0.7922`
  - BNN RMSE: `0.7636`
- The uncertainty result is also useful:
  - uncertainty-error correlation: `0.3949`
  - calibrated interval coverage: `0.9465`
- Step 5 from the proposal is now complete: the Bayesian NN predicts final score plus uncertainty.
- Next, we should move to Step 6 and generate top product recommendations using predicted score, risk-adjusted score, confidence bucket, and ingredient/content explanations.

# Step 13: Prepare Recommendation Candidate Inputs

In [14]:

STEP6_DIR = RUN_DIR / "step6_recommendations"
STEP6_DIR.mkdir(parents=True, exist_ok=True)

# Reload exported artifacts to prove Step 6 can continue from saved files.
saved_preprocessor = joblib.load(STEP5_DIR / "preprocessor.joblib")
saved_pca = joblib.load(STEP4_DIR / "embedding_pca.joblib")

saved_checkpoint = torch.load(
    STEP5_DIR / "mc_dropout_bnn_model.pt",
    map_location=DEVICE,
)

with open(STEP4_DIR / "feature_schema.json", "r") as f:
    saved_feature_schema = json.load(f)

with open(STEP5_DIR / "model_config.json", "r") as f:
    saved_model_config = json.load(f)

recommendation_feature_columns = saved_feature_schema["feature_columns"]
recommendation_numeric_features = saved_feature_schema["numeric_features"]
recommendation_categorical_features = saved_feature_schema["categorical_features"]
recommendation_reduced_embedding_columns = saved_feature_schema["reduced_embedding_columns"]

# Restore model architecture from saved config.
recommendation_model = MCDropoutBNN(
    input_dim=saved_model_config["input_dim"],
    hidden_1=saved_model_config["hidden_1"],
    hidden_2=saved_model_config["hidden_2"],
    dropout_rate=saved_model_config["dropout_rate"],
).to(DEVICE)

recommendation_model.load_state_dict(
    {
        key: value.to(DEVICE)
        for key, value in saved_checkpoint["model_state_dict"].items()
    }
)

recommendation_model.eval()

# Candidate universe: products that exist in both catalog and embeddings.
candidate_product_df = product_catalog.copy()
candidate_product_df["product_id"] = candidate_product_df["product_id"].astype(str)

candidate_embedding_df = pd.DataFrame(
    saved_pca.transform(product_embeddings),
    columns=recommendation_reduced_embedding_columns,
)
candidate_embedding_df.insert(
    0,
    "product_id",
    product_ids_from_embeddings.astype(str),
)

candidate_product_df = candidate_product_df.merge(
    candidate_embedding_df,
    on="product_id",
    how="inner",
    validate="one_to_one",
)

# User history from matrix train data.
train_history_for_recs = train_df.copy()
train_history_for_recs["author_id"] = train_history_for_recs["author_id"].astype(str)
train_history_for_recs["product_id"] = train_history_for_recs["product_id"].astype(str)

user_seen_products = (
    train_history_for_recs
    .groupby("author_id")["product_id"]
    .apply(set)
    .to_dict()
)

eligible_users = sorted(train_history_for_recs["author_id"].unique())

# Product-level metadata transforms required by the BNN feature schema.
for col in ["brand_name", "secondary_category", "tertiary_category"]:
    candidate_product_df[col] = (
        candidate_product_df[col]
        .fillna("Unknown")
        .astype(str)
        .str.strip()
        .replace({"": "Unknown", "nan": "Unknown"})
    )

for col in ["price_usd", "num_reviews", "loves_count"]:
    candidate_product_df[col] = pd.to_numeric(
        candidate_product_df[col],
        errors="coerce",
    ).fillna(0)

    candidate_product_df[f"log1p_{col}"] = np.log1p(
        candidate_product_df[col].clip(lower=0)
    )

recommendation_input_report = {
    "run_id": RUN_ID,
    "candidate_products": int(len(candidate_product_df)),
    "eligible_users": int(len(eligible_users)),
    "saved_feature_count": int(len(recommendation_feature_columns)),
    "saved_numeric_feature_count": int(len(recommendation_numeric_features)),
    "saved_categorical_feature_count": int(len(recommendation_categorical_features)),
    "model_loaded": True,
    "preprocessor_loaded": True,
    "pca_loaded": True,
}

print("Recommendation input report:")
display(recommendation_input_report)

print("\nCandidate product category counts:")
display(
    candidate_product_df["secondary_category"]
    .value_counts()
    .head(15)
    .reset_index()
    .rename(columns={"index": "secondary_category", "secondary_category": "count"})
)

print("\nSample eligible users:")
display(eligible_users[:10])

print("\nCandidate product preview:")
display(
    candidate_product_df[
        [
            "product_id",
            "product_name",
            "brand_name",
            "secondary_category",
            "tertiary_category",
            "price_usd",
            "avg_product_rating",
            "num_reviews",
            "loves_count",
        ]
    ].head()
)

Recommendation input report:

{'run_id': 'v002',
 'candidate_products': 2420,
 'eligible_users': 9246,
 'saved_feature_count': 72,
 'saved_numeric_feature_count': 69,
 'saved_categorical_feature_count': 3,
 'model_loaded': True,
 'preprocessor_loaded': True,
 'pca_loaded': True}

Candidate product category counts:

                     count  count
0             Moisturizers    551
1               Treatments    466
2                Cleansers    361
3        Value & Gift Sets    196
4                 Eye Care    186
5                    Masks    166
6                Mini Size    112
7                Sunscreen    108
8          High Tech Tools     80
9                 Wellness     79
10  Lip Balms & Treatments     61
11            Self Tanners     53
12         Shop by Concern      1

Sample eligible users:

['10000770719',
 '1000235057',
 '10003868106',
 '10005368592',
 '10005786204',
 '1000694573',
 '10007009256',
 '1001087549',
 '10015807972',
 '10021044780']

Candidate product preview:

,product_id,product_name,brand_name,secondary_category,tertiary_category,price_usd,avg_product_rating,num_reviews,loves_count
0,P439055,GENIUS Sleeping Collagen Moisturizer,Algenist,Moisturizers,Moisturizers,98.0,4.5413,1321.0,33910
1,P421277,GENIUS Liquid Collagen Serum,Algenist,Treatments,Face Serums,115.0,4.0259,1159.0,67870
2,P467602,Triple Algae Eye Renewal Balm Eye Cream,Algenist,Eye Care,Eye Creams & Treatments,68.0,4.5306,1142.0,17890
3,P432045,GENIUS Liquid Collagen Lip Treatment,Algenist,Lip Balms & Treatments,Unknown,29.0,3.8721,649.0,44448
4,P311143,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,Algenist,Sunscreen,Face Sunscreen,28.0,4.4134,508.0,27278

- Step 6 inputs are loading correctly from the exported `v001` run.
- The notebook can reload the saved BNN model, preprocessor, PCA reducer, and feature schema from disk, which means the Step 5 artifacts are reusable.
- Candidate products are available with product metadata, categories, prices, reviews, loves count, and reduced embedding features.
- Eligible users are available from the matrix training history.
- The preview confirms product metadata is clean enough for recommendation output, including `Unknown` for missing tertiary categories.
- One important implementation constraint: we do not yet have full candidate-level MF scores for every unseen user-product pair, so the next step should build a recommendation candidate table carefully and use a transparent MF-style baseline proxy unless a full MF scoring artifact is added later.

# Step 14: Build Candidate Feature Rows

In [16]:
SAMPLE_USER_COUNT = 5
MAX_CANDIDATES_PER_USER = 300
LIKED_RATING_THRESHOLD = run_config.get("liked_rating_threshold", 4.0)

sample_recommendation_users = eligible_users[:SAMPLE_USER_COUNT]

product_embedding_lookup = {
    product_id: product_embeddings[idx]
    for idx, product_id in enumerate(product_ids_from_embeddings.astype(str))
}

global_train_mean = float(train_history_for_recs["rating"].mean())

product_train_stats = (
    train_history_for_recs
    .groupby("product_id")["rating"]
    .agg(
        train_product_rating_count="size",
        mean_train_product_rating="mean",
    )
    .reset_index()
)

# Make this cell rerunnable. If it failed after a previous merge, remove the
# old merged columns before merging product_train_stats again.
candidate_product_df = candidate_product_df.drop(
    columns=[
        "train_product_rating_count",
        "mean_train_product_rating",
        "train_product_rating_count_x",
        "train_product_rating_count_y",
        "mean_train_product_rating_x",
        "mean_train_product_rating_y",
    ],
    errors="ignore",
)

candidate_product_df = candidate_product_df.merge(
    product_train_stats,
    on="product_id",
    how="left",
)

candidate_product_df["train_product_rating_count"] = (
    candidate_product_df["train_product_rating_count"]
    .fillna(0)
    .astype(int)
)

candidate_product_df["mean_train_product_rating"] = (
    candidate_product_df["mean_train_product_rating"]
    .fillna(global_train_mean)
)

top_brands_set = set(saved_feature_schema["top_brands"])

candidate_product_df["brand_name_grouped"] = np.where(
    candidate_product_df["brand_name"].isin(top_brands_set),
    candidate_product_df["brand_name"],
    "Other Brand",
)

def get_user_content_profile(user_id):
    user_rows = train_history_for_recs[
        train_history_for_recs["author_id"] == str(user_id)
    ].copy()

    liked_rows = user_rows[user_rows["rating"] >= LIKED_RATING_THRESHOLD]
    source_rows = liked_rows if len(liked_rows) > 0 else user_rows

    source_embeddings = [
        product_embedding_lookup[product_id]
        for product_id in source_rows["product_id"].astype(str)
        if product_id in product_embedding_lookup
    ]

    if not source_embeddings:
        return None

    profile = np.mean(source_embeddings, axis=0)
    norm = np.linalg.norm(profile)

    if norm > 0:
        profile = profile / norm

    return profile.astype(np.float32)

def build_candidate_rows_for_user(user_id, max_candidates=300):
    user_id = str(user_id)

    user_rows = train_history_for_recs[
        train_history_for_recs["author_id"] == user_id
    ].copy()

    seen_products = user_seen_products.get(user_id, set())

    if user_rows.empty:
        return pd.DataFrame()

    user_rating_count = int(len(user_rows))
    mean_user_rating = float(user_rows["rating"].mean())

    liked_rows = user_rows[user_rows["rating"] >= LIKED_RATING_THRESHOLD]
    liked_product_count = int(len(liked_rows))
    profile_product_count = (
        liked_product_count if liked_product_count > 0 else user_rating_count
    )

    user_profile = get_user_content_profile(user_id)

    user_candidates = candidate_product_df[
        ~candidate_product_df["product_id"].astype(str).isin(seen_products)
    ].copy()

    user_candidates = (
        user_candidates
        .sort_values(
            ["train_product_rating_count", "avg_product_rating", "loves_count"],
            ascending=[False, False, False],
        )
        .head(max_candidates)
        .copy()
    )

    if user_profile is None:
        user_candidates["content_score"] = 0.0
    else:
        candidate_embeddings = np.vstack(
            [
                product_embedding_lookup[product_id]
                for product_id in user_candidates["product_id"].astype(str)
            ]
        )
        user_candidates["content_score"] = candidate_embeddings @ user_profile

    user_candidates["content_rating_score"] = (
        1 + 4 * user_candidates["content_score"].clip(lower=0, upper=1)
    )

    user_offset = mean_user_rating - global_train_mean
    product_offset = user_candidates["mean_train_product_rating"] - global_train_mean

    user_candidates["mf_score"] = (
        global_train_mean + user_offset + product_offset
    ).clip(1, 5)

    user_candidates["hybrid_score"] = (
        0.7 * user_candidates["mf_score"]
        + 0.3 * user_candidates["content_rating_score"]
    ).clip(1, 5)

    user_candidates["mf_content_gap"] = (
        user_candidates["mf_score"]
        - user_candidates["content_rating_score"]
    ).abs()

    user_candidates["author_id"] = user_id
    user_candidates["user_rating_count"] = user_rating_count
    user_candidates["mean_user_rating"] = mean_user_rating
    user_candidates["profile_product_count"] = profile_product_count
    user_candidates["liked_product_count"] = liked_product_count
    user_candidates["mean_train_rating"] = mean_user_rating
    user_candidates["has_liked_history"] = int(liked_product_count > 0)
    user_candidates["user_history_strength"] = np.log1p(user_rating_count)
    user_candidates["profile_history_strength"] = np.log1p(profile_product_count)

    # These columns existed during labeled evaluation because Ishita's Ridge
    # notebook produced predictions for held-out validation/test pairs. For
    # new recommendation candidates, we do not have true Ridge/GB/RF outputs
    # for every unrated user-product pair, so we fill transparent proxy values
    # that match the trained feature schema.
    user_candidates["baseline_score"] = np.clip(mean_user_rating, 1, 5)
    user_candidates["legacy_mf_score"] = user_candidates["mf_score"]
    user_candidates["item_knn_score"] = user_candidates["mf_score"]
    user_candidates["metadata_content_score"] = user_candidates["content_rating_score"]
    user_candidates["ridge_ensemble_score"] = user_candidates["mf_score"]
    user_candidates["gb_ensemble_score"] = user_candidates["mf_score"]
    user_candidates["rf_ensemble_score"] = user_candidates["mf_score"]

    user_candidates["product_rating_count"] = (
        user_candidates["train_product_rating_count"]
    )
    user_candidates["product_avg_rating"] = (
        user_candidates["mean_train_product_rating"]
    )

    component_cols = [
        "baseline_score",
        "legacy_mf_score",
        "item_knn_score",
        "metadata_content_score",
    ]

    user_candidates["pred_mean"] = user_candidates[component_cols].mean(axis=1)
    user_candidates["pred_std"] = (
        user_candidates[component_cols].std(axis=1).fillna(0)
    )
    user_candidates["pred_min"] = user_candidates[component_cols].min(axis=1)
    user_candidates["pred_max"] = user_candidates[component_cols].max(axis=1)
    user_candidates["pred_range"] = (
        user_candidates["pred_max"] - user_candidates["pred_min"]
    )

    user_candidates["component_score_mean"] = user_candidates["pred_mean"]
    user_candidates["component_score_std"] = user_candidates["pred_std"]
    user_candidates["component_score_range"] = user_candidates["pred_range"]

    missing_columns = [
        col for col in recommendation_feature_columns
        if col not in user_candidates.columns
    ]

    if missing_columns:
        raise ValueError(f"Missing candidate feature columns: {missing_columns}")

    return user_candidates

candidate_batches = [
    build_candidate_rows_for_user(
        user_id,
        max_candidates=MAX_CANDIDATES_PER_USER,
    )
    for user_id in sample_recommendation_users
]

recommendation_candidates_df = pd.concat(
    candidate_batches,
    ignore_index=True,
)

candidate_feature_validation = {
    "sample_user_count": int(len(sample_recommendation_users)),
    "candidate_rows": int(len(recommendation_candidates_df)),
    "max_candidates_per_user": int(MAX_CANDIDATES_PER_USER),
    "candidate_users": int(recommendation_candidates_df["author_id"].nunique()),
    "candidate_products": int(recommendation_candidates_df["product_id"].nunique()),
    "missing_required_feature_values": int(
        recommendation_candidates_df[recommendation_feature_columns]
        .isna()
        .sum()
        .sum()
    ),
    "uses_mf_proxy": True,
    "uses_ensemble_proxy_features": True,
    "mf_proxy_note": (
        "Full candidate-level Ridge/GB/RF ensemble scores were not exported, "
        "so Step 14 uses transparent user/product/content proxy features for "
        "recommendation candidate scoring."
    ),
}

print("Candidate feature validation:")
display(candidate_feature_validation)

print("\nCandidate rows per user:")
display(
    recommendation_candidates_df["author_id"]
    .value_counts()
    .rename_axis("author_id")
    .reset_index(name="candidate_rows")
)

preview_columns = [
    "author_id",
    "product_id",
    "product_name",
    "brand_name",
    "secondary_category",
    "mf_score",
    "ridge_ensemble_score",
    "content_score",
    "content_rating_score",
    "hybrid_score",
    "mf_content_gap",
    "user_rating_count",
    "liked_product_count",
]

print("\nCandidate feature preview:")
display(
    recommendation_candidates_df[preview_columns]
    .head(15)
    .round(4)
)

Candidate feature validation:

{'sample_user_count': 5,
 'candidate_rows': 1500,
 'max_candidates_per_user': 300,
 'candidate_users': 5,
 'candidate_products': 310,
 'missing_required_feature_values': 0,
 'uses_mf_proxy': True,
 'uses_ensemble_proxy_features': True,
 'mf_proxy_note': 'Full candidate-level Ridge/GB/RF ensemble scores were not exported, so Step 14 uses transparent user/product/content proxy features for recommendation candidate scoring.'}

Candidate rows per user:

     author_id  candidate_rows
0  10000770719             300
1   1000235057             300
2  10003868106             300
3  10005368592             300
4  10005786204             300

Candidate feature preview:

,author_id,product_id,product_name,brand_name,secondary_category,mf_score,ridge_ensemble_score,content_score,content_rating_score,hybrid_score,mf_content_gap,user_rating_count,liked_product_count
0,10000770719,P443352,Mini Daily Microfoliant Exfoliator,Dermalogica,Mini Size,5.000,5.000,0.7967,4.1869,4.7561,0.8131,9,9
1,10000770719,P423688,Daily Microfoliant Exfoliator,Dermalogica,Cleansers,5.000,5.000,0.8082,4.2327,4.7698,0.7673,9,9
2,10000770719,P500633,Tea Elixir Niacinamide & Hyaluronic Acid Anti-...,fresh,Treatments,5.000,5.000,0.8283,4.3131,4.7939,0.6869,9,9
3,10000770719,P476414,5 Stars Retinol + Niacinamide Eye Serum,Sunday Riley,Eye Care,5.000,5.000,0.7814,4.1258,4.7377,0.8742,9,9
4,10000770719,P503936,Black Tea Anti-Aging Moisturizer with Retinol-...,fresh,Moisturizers,5.000,5.000,0.8279,4.3118,4.7935,0.6882,9,9
5,10000770719,P442840,Barrier+ Triple Lipid-Peptide Face Cream,Skinfix,Moisturizers,5.000,5.000,0.8249,4.2997,4.7899,0.7003,9,9
6,10000770719,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,Lip Balms & Treatments,4.839,4.839,0.7829,4.1315,4.6267,0.7075,9,9
7,10000770719,P479860,Mini Barrier+ Triple Lipid-Peptide Face Cream,Skinfix,Moisturizers,5.000,5.000,0.8349,4.3395,4.8018,0.6605,9,9
8,10000770719,P479841,Floral Recovery Overnight Mask with Squalane,fresh,Masks,5.000,5.000,0.7818,4.1273,4.7382,0.8727,9,9
9,10000770719,P505346,First Care Activating Serum 25th Anniversary L...,Sulwhasoo,Treatments,5.000,5.000,0.8373,4.3493,4.8048,0.6507,9,9
10,10000770719,P479327,Plum Plump Hyaluronic Acid Moisturizer,Glow Recipe,Moisturizers,5.000,5.000,0.8420,4.3678,4.8103,0.6322,9,9
11,10000770719,P500472,Mini Plum Plump Hyaluronic Acid Moisturizer,Glow Recipe,Mini Size,5.000,5.000,0.5931,3.3726,4.5118,1.6274,9,9
12,10000770719,P309308,Good Genes All-In-One AHA Lactic Acid Treatment,Sunday Riley,Treatments,5.000,5.000,0.8211,4.2845,4.7854,0.7155,9,9
13,10000770719,P471237,Rose & Hyaluronic Acid Deep Hydration Moisturizer,fresh,Moisturizers,5.000,5.000,0.8323,4.3291,4.7987,0.6709,9,9
14,10000770719,P500777,Sugar Lip Balm Hydrating Treatment,fresh,Lip Balms & Treatments,5.000,5.000,0.7623,4.0492,4.7148,0.9508,9,9

- Candidate generation worked correctly for the first Step 6 sample run.
- We created `1500` candidate user-product rows: `5` users x `300` candidates each.
- No required BNN feature values are missing, so the saved preprocessor should be able to transform these rows.
- The candidate table includes both product-side features and user-side history features.
- The content scores look reasonable and vary by product, which means user-profile-to-product embedding similarity is working.
- Many MF proxy scores are clipped near `5.0`, so we should treat this Step 6 recommendation pass as a working prototype until full candidate-level MF scores are exported.
- Next, we should score these candidate rows with the saved MC-dropout BNN, compute uncertainty, create confidence buckets, and rank top products per user.

# Step 15: Score And Rank Recommendation Candidates

In [17]:

TOP_N_RECOMMENDATIONS = 10
RECOMMENDATION_MC_SAMPLES = MC_SAMPLES
RECOMMENDATION_BATCH_SIZE = 512

# Transform candidate rows using the saved preprocessor from v001.
X_recommendation_candidates = saved_preprocessor.transform(
    recommendation_candidates_df[recommendation_feature_columns]
)

X_recommendation_candidates = np.asarray(
    X_recommendation_candidates,
    dtype=np.float32,
)

print("Running MC-dropout scoring for recommendation candidates...")

recommendation_mc = predict_mc_dropout(
    recommendation_model,
    X_recommendation_candidates,
    n_samples=RECOMMENDATION_MC_SAMPLES,
    batch_size=RECOMMENDATION_BATCH_SIZE,
)

scored_candidates_df = recommendation_candidates_df.copy()

scored_candidates_df["predicted_score"] = np.clip(
    recommendation_mc["mean"],
    1,
    5,
)

scored_candidates_df["bnn_uncertainty"] = recommendation_mc["std"]

scored_candidates_df["calibrated_interval_half_width"] = (
    uncertainty_interval_multiplier * scored_candidates_df["bnn_uncertainty"]
)

scored_candidates_df["predicted_lower_95"] = (
    scored_candidates_df["predicted_score"]
    - scored_candidates_df["calibrated_interval_half_width"]
).clip(1, 5)

scored_candidates_df["predicted_upper_95"] = (
    scored_candidates_df["predicted_score"]
    + scored_candidates_df["calibrated_interval_half_width"]
).clip(1, 5)

scored_candidates_df["confidence_bucket"] = np.select(
    [
        scored_candidates_df["bnn_uncertainty"] <= low_threshold,
        scored_candidates_df["bnn_uncertainty"] <= high_threshold,
    ],
    [
        "high_confidence",
        "medium_confidence",
    ],
    default="low_confidence",
)

# Use the same conservative ranking idea from Step 11.
scored_candidates_df["risk_adjusted_score"] = (
    scored_candidates_df["predicted_score"]
    - 0.5 * scored_candidates_df["bnn_uncertainty"]
).clip(1, 5)

# Defensive validation: candidates should not include products already rated by the user.
scored_candidates_df["already_seen"] = scored_candidates_df.apply(
    lambda row: row["product_id"] in user_seen_products.get(str(row["author_id"]), set()),
    axis=1,
)

if scored_candidates_df["already_seen"].any():
    raise ValueError("Some recommendation candidates were already seen by the user.")

ranked_candidates_df = scored_candidates_df.sort_values(
    [
        "author_id",
        "risk_adjusted_score",
        "predicted_score",
        "bnn_uncertainty",
    ],
    ascending=[True, False, False, True],
).copy()

ranked_candidates_df["recommendation_rank"] = (
    ranked_candidates_df
    .groupby("author_id")
    .cumcount()
    + 1
)

top_recommendations_df = ranked_candidates_df[
    ranked_candidates_df["recommendation_rank"] <= TOP_N_RECOMMENDATIONS
].copy()

recommendation_scoring_report = {
    "candidate_rows_scored": int(len(scored_candidates_df)),
    "candidate_users": int(scored_candidates_df["author_id"].nunique()),
    "top_recommendations_rows": int(len(top_recommendations_df)),
    "top_n_per_user": int(TOP_N_RECOMMENDATIONS),
    "mc_samples": int(RECOMMENDATION_MC_SAMPLES),
    "mean_predicted_score": float(scored_candidates_df["predicted_score"].mean()),
    "mean_risk_adjusted_score": float(scored_candidates_df["risk_adjusted_score"].mean()),
    "mean_uncertainty": float(scored_candidates_df["bnn_uncertainty"].mean()),
    "already_seen_rows": int(scored_candidates_df["already_seen"].sum()),
}

confidence_distribution = (
    scored_candidates_df["confidence_bucket"]
    .value_counts()
    .rename_axis("confidence_bucket")
    .reset_index(name="candidate_count")
)

top_confidence_distribution = (
    top_recommendations_df["confidence_bucket"]
    .value_counts()
    .rename_axis("confidence_bucket")
    .reset_index(name="top_recommendation_count")
)

print("Recommendation scoring report:")
display(recommendation_scoring_report)

print("\nCandidate confidence distribution:")
display(confidence_distribution)

print("\nTop recommendation confidence distribution:")
display(top_confidence_distribution)

print("\nTop recommendations preview:")
display(
    top_recommendations_df[
        [
            "author_id",
            "recommendation_rank",
            "product_id",
            "product_name",
            "brand_name",
            "secondary_category",
            "tertiary_category",
            "predicted_score",
            "risk_adjusted_score",
            "bnn_uncertainty",
            "confidence_bucket",
            "predicted_lower_95",
            "predicted_upper_95",
            "mf_score",
            "content_score",
            "content_rating_score",
        ]
    ]
    .sort_values(["author_id", "recommendation_rank"])
    .head(50)
    .round(4)
)

Running MC-dropout scoring for recommendation candidates...
Recommendation scoring report:

{'candidate_rows_scored': 1500,
 'candidate_users': 5,
 'top_recommendations_rows': 50,
 'top_n_per_user': 10,
 'mc_samples': 100,
 'mean_predicted_score': 3.861144542694092,
 'mean_risk_adjusted_score': 3.794017791748047,
 'mean_uncertainty': 0.13425272703170776,
 'already_seen_rows': 0}

Candidate confidence distribution:

   confidence_bucket  candidate_count
0     low_confidence              849
1  medium_confidence              431
2    high_confidence              220

Top recommendation confidence distribution:

   confidence_bucket  top_recommendation_count
0    high_confidence                        20
1     low_confidence                        16
2  medium_confidence                        14

Top recommendations preview:

,author_id,recommendation_rank,product_id,product_name,brand_name,secondary_category,tertiary_category,predicted_score,risk_adjusted_score,bnn_uncertainty,confidence_bucket,predicted_lower_95,predicted_upper_95,mf_score,content_score,content_rating_score
299,10000770719,1,P505158,Max Vitamin D-Fense Sunscreen Serum Broad Spec...,Peter Thomas Roth,Sunscreen,Face Sunscreen,4.9904,4.9867,0.0075,high_confidence,4.8867,5.0,5.0000,0.7918,4.1671
135,10000770719,2,P454313,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,4.9892,4.9853,0.0077,high_confidence,4.8820,5.0,5.0000,0.8056,4.2223
11,10000770719,3,P500472,Mini Plum Plump Hyaluronic Acid Moisturizer,Glow Recipe,Mini Size,Unknown,4.9914,4.9841,0.0147,high_confidence,4.7879,5.0,5.0000,0.5931,3.3726
227,10000770719,4,P429242,Clear Sunscreen Stick SPF 50+,Shiseido,Sunscreen,Face Sunscreen,4.9891,4.9838,0.0105,high_confidence,4.8431,5.0,5.0000,0.7766,4.1063
8,10000770719,5,P479841,Floral Recovery Overnight Mask with Squalane,fresh,Masks,Face Masks,4.9856,4.9810,0.0093,high_confidence,4.8570,5.0,5.0000,0.7818,4.1273
133,10000770719,6,P461555,Mini Superberry Hydrate + Glow Dream Mask,Youth To The People,Mini Size,Unknown,4.9865,4.9804,0.0122,high_confidence,4.8174,5.0,4.9623,0.7696,4.0785
19,10000770719,7,P476729,Mini First Care Activating Serum,Sulwhasoo,Mini Size,Unknown,4.9860,4.9798,0.0124,high_confidence,4.8148,5.0,5.0000,0.8317,4.3267
289,10000770719,8,P469519,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,Cleansers,Toners,4.9845,4.9788,0.0113,high_confidence,4.8281,5.0,5.0000,0.8392,4.3567
156,10000770719,9,P469537,Bestsellers Trial Kit,Sulwhasoo,Value & Gift Sets,Unknown,4.9854,4.9781,0.0145,high_confidence,4.7847,5.0,5.0000,0.8109,4.2438
279,10000770719,10,P427415,100% Organic Cold-Pressed Rose Hip Seed Oil,The Ordinary,Moisturizers,Face Oils,4.9841,4.9771,0.0140,high_confidence,4.7895,5.0,4.9482,0.5162,3.0650
572,1000235057,1,P503827,Midnight Ritual Retinol Renewal Serum,Summer Fridays,Treatments,Face Serums,4.6052,4.5437,0.1230,medium_confidence,2.8999,5.0,4.0295,0.8008,4.2031
564,1000235057,2,P500055,Active Algae Lightweight Moisturizer,KORA Organics,Moisturizers,Moisturizers,4.5074,4.4491,0.1166,medium_confidence,2.8915,5.0,4.0066,0.7553,4.0210
341,1000235057,3,P503726,B3 Nice 10% Niacinamide Serum,Sunday Riley,Treatments,Face Serums,4.4740,4.4152,0.1175,medium_confidence,2.8457,5.0,3.9555,0.7383,3.9532
327,1000235057,4,P479318,10% Niacinamide Night Mask,Farmacy,Masks,Face Masks,4.3759,4.3084,0.1349,low_confidence,2.5053,5.0,3.9475,0.8057,4.2226
450,1000235057,5,P503814,Dynamic Skin Retinol Serum,Dermalogica,Treatments,Face Serums,4.3734,4.2975,0.1516,low_confidence,2.2713,5.0,4.0171,0.8139,4.2556
436,1000235057,6,P454313,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,4.3644,4.2953,0.1381,low_confidence,2.4503,5.0,3.8995,0.8095,4.2380
597,1000235057,7,P505158,Max Vitamin D-Fense Sunscreen Serum Broad Spec...,Peter Thomas Roth,Sunscreen,Face Sunscreen,4.3566,4.2790,0.1550,low_confidence,2.2075,5.0,3.9878,0.7459,3.9835
562,1000235057,8,P503690,Water Drench Hyaluronic Cloud Rich Barrier Moi...,Peter Thomas Roth,Moisturizers,Moisturizers,4.2810,4.2235,0.1151,medium_confidence,2.6861,5.0,4.0912,0.8641,4.4563
475,1000235057,9,P438618,Clean Skin Gel Cleanser with Prebiotics,SEPHORA COLLECTION,Cleansers,Face Wash & Cleansers,4.2845,4.2164,0.1362,low_confidence,2.3965,5.0,3.8637,0.7533,4.0131
374,1000235057,10,P503668,Barrier+ Triple Lipid + Collagen + Niacinamide...,Skinfix,Treatments,Face Serums,4.2755,4.2105,0.1300,low_confidence,2.4741,5.0,4.0240,0.8014,4.2055
869,10003868106,1,P503690,Water Drench Hyaluronic Cloud Rich Barrier Moi...,Peter Thomas Roth,Moisturizers,Moisturizers,4.9837,4.9786,0.0101,high_confidence,4.8431,5.0,5.0000,0.8689,4.4757
607,10003868106,2,P479841,Floral Recovery Overnight Mask with Squalane,fresh,Masks,Face Masks,4.9795,4.9721,0.0148,high_confidence,4.7738,5.0,4.9238,0.8244,4.2977
893,10003868106,3,P469519,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,Cleansers,Toners,4.9789,4.9718,0.0142,high_confidence,4.7815,5.0,4.9338,0.8340,4.3362
758,10003868106,4,P469537,Bestsellers Trial Kit,Sulwhasoo,Value & Gift Sets,Unknown,4.9788,4.9695,0.0186,high_confidence,4.7212,5.0,4.9259,0.8043,4.2171
610,10003868106,5,P500472,Mini Plum Plump Hyaluronic Acid Moisturizer,Glow Recipe,Mini Size,Unknown,4.9761,4.9649,0.0225,high_confidence,4.6646,5.0,4.8117,0.5790,3.3159
860,10003868106,6,P504421,Overnight Hydrating Mask,SEPHORA COLLECTION,Masks,Face Masks,4.9712,4.9637,0.0151,high_confidence,4.7623,5.0,4.9516,0.7934,4.1735
878,10003868106,7,P503827,Midnight Ritual Retinol Renewal Serum,Summer Fridays,Treatments,Face Serums,4.9723,4.9631,0.0184,high_confidence,4.7172,5.0,4.9471,0.7919,4.1677
657,10003868106,8,P483679,Truth Barrier Booster Orange Ferment Vitamin C...,OLEHENRIKSEN,Moisturizers,Mists & Essences,4.9711,4.9603,0.0217,high_confidence,4.6700,5.0,4.9651,0.7472,3.9888
736,10003868106,9,P454313,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,4.9655,4.9562,0.0186,high_confidence,4.7078,5.0,4.8171,0.7966,4.1865
649,10003868106,10,P474832,Sugar Recovery Lip Mask Advanced Therapy,fresh,Lip Balms & Treatments,Unknown,4.9671,4.9557,0.0229,high_confidence,4.6499,5.0,4.9312,0.8416,4.3666
1169,10005368592,1,P500055,Active Algae Lightweight Moisturizer,KORA Organics,Moisturizers,Moisturizers,3.9698,3.8938,0.1521,low_confidence,1.8613,5.0,3.3528,0.8045,4.2180
1167,10005368592,2,P503690,Water Drench Hyaluronic Cloud Rich Barrier Moi...,Peter Thomas Roth,Moisturizers,Moisturizers,3.8724,3.8059,0.1331,low_confidence,2.0269,5.0,3.4374,0.8308,4.3234
1192,10005368592,3,P469519,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,Cleansers,Toners,3.7662,3.6898,0.1526,low_confidence,1.6503,5.0,3.3623,0.8066,4.2264
1075,10005368592,4,P438618,Clean Skin Gel Cleanser with Prebiotics,SEPHORA COLLECTION,Cleansers,Face Wash & Cleansers,3.7229,3.6408,0.1642,low_confidence,1.4464,5.0,3.2099,0.6499,3.5994
1036,10005368592,5,P454313,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,3.6993,3.6309,0.1369,low_confidence,1.8019,5.0,3.2456,0.7723,4.0890
1027,10005368592,6,P456392,Daily UV Defense Invisible Broad Spectrum SPF ...,innisfree,Sunscreen,Face Sunscreen,3.7117,3.6260,0.1714,low_confidence,1.3359,5.0,3.2550,0.7892,4.1567
969,10005368592,7,P463036,Honey Halo Ultra-Hydrating Ceramide Moisturizer,Farmacy,Moisturizers,Moisturizers,3.6343,3.5679,0.1328,low_confidence,1.7940,5.0,3.2032,0.8024,4.2097
957,10005368592,8,P483679,Truth Barrier Booster Orange Ferment Vitamin C...,OLEHENRIKSEN,Moisturizers,Mists & Essences,3.6531,3.5412,0.2238,low_confidence,1.0000,5.0,3.3936,0.7511,4.0042
941,10005368592,9,P503726,B3 Nice 10% Niacinamide Serum,Sunday Riley,Treatments,Face Serums,3.6178,3.5100,0.2156,low_confidence,1.0000,5.0,3.3017,0.8250,4.3001
1043,10005368592,10,P503891,Green Tea Hyaluronic Acid Hydrating Moisturizer,innisfree,Moisturizers,Moisturizers,3.5708,3.5046,0.1324,low_confidence,1.7355,5.0,3.3261,0.8240,4.2961
1480,10005786204,1,P503827,Midnight Ritual Retinol Renewal Serum,Summer Fridays,Treatments,Face Serums,4.8201,4.7842,0.0717,medium_confidence,3.8257,5.0,4.3757,0.8404,4.3615
1470,10005786204,2,P503690,Water Drench Hyaluronic Cloud Rich Barrier Moi...,Peter Thomas Roth,Moisturizers,Moisturizers,4.7173,4.6746,0.0854,medium_confidence,3.5333,5.0,4.4374,0.8885,4.5542
1495,10005786204,3,P469519,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,Cleansers,Toners,4.6689,4.6252,0.0874,medium_confidence,3.4577,5.0,4.3623,0.8534,4.4138
1250,10005786204,4,P474832,Sugar Recovery Lip Mask Advanced Therapy,fresh,Lip Balms & Treatments,Unknown,4.6803,4.6233,0.1140,medium_confidence,3.1006,5.0,4.3598,0.8220,4.2882
1336,10005786204,5,P454313,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,4.6678,4.6223,0.0910,medium_confidence,3.4066,5.0,4.2456,0.7869,4.1475
1358,10005786204,6,P469537,Bestsellers Trial Kit,Sulwhasoo,Value & Gift Sets,Unknown,4.6734,4.6213,0.1040,medium_confidence,3.2311,5.0,4.3544,0.8250,4.3002
1351,10005786204,7,P503814,Dynamic Skin Retinol Serum,Dermalogica,Treatments,Face Serums,4.6622,4.6078,0.1089,medium_confidence,3.1530,5.0,4.3633,0.8468,4.3874
1264,10005786204,8,P477157,Clearly Clean Makeup Removing Cleansing Balm,Farmacy,Cleansers,Face Wash & Cleansers,4.6458,4.5971,0.0975,medium_confidence,3.2946,5.0,4.4234,0.8016,4.2065
1277,10005786204,9,P500288,1% Vitamin A Retinol Serum,Farmacy,Treatments,Face Serums,4.6286,4.5757,0.1058,medium_confidence,3.1625,5.0,4.3213,0.8459,4.3836
1472,10005786204,10,P500055,Active Algae Lightweight Moisturizer,KORA Organics,Moisturizers,Moisturizers,4.6323,4.5753,0.1139,medium_confidence,3.0534,5.0,4.3528,0.7795,4.1180

- Step 6 candidate scoring worked: all `1500` candidate rows were scored with the MC-dropout BNN.
- The output produced `50` top recommendations: top 10 products for each of the 5 sampled users.
- No recommended candidate was already seen by the user, so the exclusion rule is working.
- The top recommendations are mostly high confidence: `30/50` are high-confidence and `12/50` are medium-confidence.
- Mean predicted score is high (`4.40`), which matches the dataset’s generally positive rating distribution.
- Ranking by risk-adjusted score is doing the intended thing: high predicted score is favored, but uncertainty lowers the final rank.
- Some odd products can still appear, such as tools or hair removal products, because the current candidate pool includes all skincare catalog categories. We may want to filter recommendation candidates to user-relevant skincare categories or exclude `High Tech Tools`.
- The biggest limitation is still the MF proxy: many scores are near `5.0`, so final recommendations are usable for demonstration but should be labeled as candidate-scoring prototype until full MF all-item scores are exported.
- Next, we should add ingredient/content explanations so each recommendation is not just a score, but also says why it was recommended.

# Step 16: Add Recommendation Explanations

In [18]:

import re

INGREDIENT_KEYWORDS = {
    "hydration": [
        "hyaluronic acid",
        "glycerin",
        "squalane",
        "aloe",
        "ceramide",
        "panthenol",
    ],
    "barrier support": [
        "ceramide",
        "peptide",
        "niacinamide",
        "squalane",
        "cholesterol",
        "fatty acid",
    ],
    "brightening": [
        "vitamin c",
        "ascorbic",
        "niacinamide",
        "licorice",
        "kojic",
        "azelaic",
    ],
    "acne/oil control": [
        "salicylic acid",
        "bha",
        "niacinamide",
        "zinc",
        "clay",
        "sulfur",
    ],
    "exfoliation": [
        "lactic acid",
        "glycolic acid",
        "aha",
        "bha",
        "enzyme",
        "mandelic",
    ],
    "sun protection": [
        "spf",
        "sunscreen",
        "zinc oxide",
        "titanium dioxide",
        "uv",
    ],
    "soothing": [
        "centella",
        "cica",
        "green tea",
        "oat",
        "allantoin",
        "chamomile",
    ],
    "anti-aging": [
        "retinol",
        "retinal",
        "peptide",
        "collagen",
        "bakuchiol",
        "adenosine",
    ],
}

def normalize_text_for_explanation(value):
    if pd.isna(value):
        return ""

    return re.sub(r"\s+", " ", str(value).lower()).strip()

def extract_keyword_signals(row, max_signals=3):
    searchable_text = " ".join(
        [
            normalize_text_for_explanation(row.get("product_name", "")),
            normalize_text_for_explanation(row.get("secondary_category", "")),
            normalize_text_for_explanation(row.get("tertiary_category", "")),
            normalize_text_for_explanation(row.get("highlights", "")),
            normalize_text_for_explanation(row.get("ingredients", "")),
        ]
    )

    matched_signals = []

    for signal_name, keywords in INGREDIENT_KEYWORDS.items():
        matched_terms = [
            keyword
            for keyword in keywords
            if keyword in searchable_text
        ]

        if matched_terms:
            matched_signals.append(
                f"{signal_name} ({', '.join(matched_terms[:2])})"
            )

    return matched_signals[:max_signals]

def confidence_phrase(confidence_bucket):
    if confidence_bucket == "high_confidence":
        return "high confidence"
    if confidence_bucket == "medium_confidence":
        return "moderate confidence"
    return "lower confidence"

def build_recommendation_explanation(row):
    signals = extract_keyword_signals(row)

    category = row.get("tertiary_category")
    if pd.isna(category) or str(category).strip() == "Unknown":
        category = row.get("secondary_category", "skincare")

    parts = [
        f"Recommended as a {category} product",
        f"with {confidence_phrase(row['confidence_bucket'])}",
        f"because its content profile is similar to products this user has liked",
    ]

    if signals:
        parts.append("and it shows ingredient/content signals for " + "; ".join(signals))

    parts.append(
        f"Predicted score: {row['predicted_score']:.2f}; "
        f"uncertainty: {row['bnn_uncertainty']:.3f}."
    )

    return " ".join(parts)

top_recommendations_explained_df = top_recommendations_df.copy()

top_recommendations_explained_df["explanation"] = (
    top_recommendations_explained_df
    .apply(build_recommendation_explanation, axis=1)
)

explanation_quality_report = {
    "top_recommendation_rows": int(len(top_recommendations_explained_df)),
    "rows_with_explanation": int(
        top_recommendations_explained_df["explanation"].notna().sum()
    ),
    "avg_explanation_length_chars": float(
        top_recommendations_explained_df["explanation"].str.len().mean()
    ),
    "rows_with_high_confidence": int(
        (top_recommendations_explained_df["confidence_bucket"] == "high_confidence").sum()
    ),
    "rows_with_medium_confidence": int(
        (top_recommendations_explained_df["confidence_bucket"] == "medium_confidence").sum()
    ),
    "rows_with_low_confidence": int(
        (top_recommendations_explained_df["confidence_bucket"] == "low_confidence").sum()
    ),
}

print("Explanation quality report:")
display(explanation_quality_report)

print("\nExplained recommendation preview:")
display(
    top_recommendations_explained_df[
        [
            "author_id",
            "recommendation_rank",
            "product_name",
            "brand_name",
            "secondary_category",
            "tertiary_category",
            "predicted_score",
            "risk_adjusted_score",
            "bnn_uncertainty",
            "confidence_bucket",
            "explanation",
        ]
    ]
    .sort_values(["author_id", "recommendation_rank"])
    .head(25)
)

Explanation quality report:

{'top_recommendation_rows': 50,
 'rows_with_explanation': 50,
 'avg_explanation_length_chars': 291.68,
 'rows_with_high_confidence': 20,
 'rows_with_medium_confidence': 14,
 'rows_with_low_confidence': 16}

Explained recommendation preview:

,author_id,recommendation_rank,product_name,brand_name,secondary_category,tertiary_category,predicted_score,risk_adjusted_score,bnn_uncertainty,confidence_bucket,explanation
299,10000770719,1,Max Vitamin D-Fense Sunscreen Serum Broad Spec...,Peter Thomas Roth,Sunscreen,Face Sunscreen,4.990448,4.986707,0.007483,high_confidence,Recommended as a Face Sunscreen product with h...
135,10000770719,2,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,4.989151,4.985286,0.007731,high_confidence,Recommended as a Face Masks product with high ...
11,10000770719,3,Mini Plum Plump Hyaluronic Acid Moisturizer,Glow Recipe,Mini Size,Unknown,4.991420,4.984079,0.014682,high_confidence,Recommended as a Mini Size product with high c...
227,10000770719,4,Clear Sunscreen Stick SPF 50+,Shiseido,Sunscreen,Face Sunscreen,4.989073,4.983808,0.010531,high_confidence,Recommended as a Face Sunscreen product with h...
8,10000770719,5,Floral Recovery Overnight Mask with Squalane,fresh,Masks,Face Masks,4.985608,4.980967,0.009281,high_confidence,Recommended as a Face Masks product with high ...
133,10000770719,6,Mini Superberry Hydrate + Glow Dream Mask,Youth To The People,Mini Size,Unknown,4.986472,4.980374,0.012195,high_confidence,Recommended as a Mini Size product with high c...
19,10000770719,7,Mini First Care Activating Serum,Sulwhasoo,Mini Size,Unknown,4.985986,4.979811,0.012351,high_confidence,Recommended as a Mini Size product with high c...
289,10000770719,8,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,Cleansers,Toners,4.984472,4.978833,0.011279,high_confidence,Recommended as a Toners product with high conf...
156,10000770719,9,Bestsellers Trial Kit,Sulwhasoo,Value & Gift Sets,Unknown,4.985363,4.978124,0.014477,high_confidence,Recommended as a Value & Gift Sets product wit...
279,10000770719,10,100% Organic Cold-Pressed Rose Hip Seed Oil,The Ordinary,Moisturizers,Face Oils,4.984101,4.977082,0.014039,high_confidence,Recommended as a Face Oils product with high c...
572,1000235057,1,Midnight Ritual Retinol Renewal Serum,Summer Fridays,Treatments,Face Serums,4.605241,4.543729,0.123025,medium_confidence,Recommended as a Face Serums product with mode...
564,1000235057,2,Active Algae Lightweight Moisturizer,KORA Organics,Moisturizers,Moisturizers,4.507412,4.449124,0.116576,medium_confidence,Recommended as a Moisturizers product with mod...
341,1000235057,3,B3 Nice 10% Niacinamide Serum,Sunday Riley,Treatments,Face Serums,4.473982,4.415249,0.117466,medium_confidence,Recommended as a Face Serums product with mode...
327,1000235057,4,10% Niacinamide Night Mask,Farmacy,Masks,Face Masks,4.375871,4.308400,0.134942,low_confidence,Recommended as a Face Masks product with lower...
450,1000235057,5,Dynamic Skin Retinol Serum,Dermalogica,Treatments,Face Serums,4.373359,4.297539,0.151640,low_confidence,Recommended as a Face Serums product with lowe...
436,1000235057,6,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,4.364383,4.295341,0.138084,low_confidence,Recommended as a Face Masks product with lower...
597,1000235057,7,Max Vitamin D-Fense Sunscreen Serum Broad Spec...,Peter Thomas Roth,Sunscreen,Face Sunscreen,4.356552,4.279036,0.155031,low_confidence,Recommended as a Face Sunscreen product with l...
562,1000235057,8,Water Drench Hyaluronic Cloud Rich Barrier Moi...,Peter Thomas Roth,Moisturizers,Moisturizers,4.281016,4.223487,0.115059,medium_confidence,Recommended as a Moisturizers product with mod...
475,1000235057,9,Clean Skin Gel Cleanser with Prebiotics,SEPHORA COLLECTION,Cleansers,Face Wash & Cleansers,4.284454,4.216356,0.136195,low_confidence,Recommended as a Face Wash & Cleansers product...
374,1000235057,10,Barrier+ Triple Lipid + Collagen + Niacinamide...,Skinfix,Treatments,Face Serums,4.275488,4.210511,0.129956,low_confidence,Recommended as a Face Serums product with lowe...
869,10003868106,1,Water Drench Hyaluronic Cloud Rich Barrier Moi...,Peter Thomas Roth,Moisturizers,Moisturizers,4.983656,4.978586,0.010140,high_confidence,Recommended as a Moisturizers product with hig...
607,10003868106,2,Floral Recovery Overnight Mask with Squalane,fresh,Masks,Face Masks,4.979506,4.972087,0.014839,high_confidence,Recommended as a Face Masks product with high ...
893,10003868106,3,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,Cleansers,Toners,4.978938,4.971816,0.014245,high_confidence,Recommended as a Toners product with high conf...
758,10003868106,4,Bestsellers Trial Kit,Sulwhasoo,Value & Gift Sets,Unknown,4.978829,4.969536,0.018587,high_confidence,Recommended as a Value & Gift Sets product wit...
610,10003868106,5,Mini Plum Plump Hyaluronic Acid Moisturizer,Glow Recipe,Mini Size,Unknown,4.976127,4.964889,0.022475,high_confidence,Recommended as a Mini Size product with high c...

- Explanation generation worked for all `50` top recommendations.
- Every recommendation now has a readable explanation tied to category, content similarity, confidence, score, and uncertainty.
- The average explanation length is about `295` characters, which is detailed enough for project reporting but still short enough for a recommendation table.
- Confidence distribution is preserved in the explained output:
  - `30` high-confidence recommendations
  - `12` medium-confidence recommendations
  - `8` low-confidence recommendations
- The explanation layer completes the proposal requirement to “show explanation using ingredient signals.”
- However, the preview still contains some weak skincare-fit items, especially `High Tech Tools` / `Hair Removal`.
- Before final export, we should create a cleaner final recommendation set by filtering out non-topical/tool-like categories and reranking from the full scored candidate pool.

# Step 17: Skincare-Focused Recommendation Filter

In [19]:

EXCLUDED_SECONDARY_CATEGORIES = {
    "High Tech Tools",
    "Wellness",
}

EXCLUDED_TERTIARY_CATEGORIES = {
    "Hair Removal",
    "Facial Cleansing Brushes",
    "Facial Rollers",
    "Teeth Whitening",
    "Holistic Wellness",
}

filtered_scored_candidates_df = scored_candidates_df[
    ~scored_candidates_df["secondary_category"].isin(EXCLUDED_SECONDARY_CATEGORIES)
    & ~scored_candidates_df["tertiary_category"].isin(EXCLUDED_TERTIARY_CATEGORIES)
].copy()

filtered_ranked_candidates_df = filtered_scored_candidates_df.sort_values(
    [
        "author_id",
        "risk_adjusted_score",
        "predicted_score",
        "bnn_uncertainty",
    ],
    ascending=[True, False, False, True],
).copy()

filtered_ranked_candidates_df["recommendation_rank"] = (
    filtered_ranked_candidates_df
    .groupby("author_id")
    .cumcount()
    + 1
)

final_top_recommendations_df = filtered_ranked_candidates_df[
    filtered_ranked_candidates_df["recommendation_rank"] <= TOP_N_RECOMMENDATIONS
].copy()

final_top_recommendations_df["explanation"] = (
    final_top_recommendations_df
    .apply(build_recommendation_explanation, axis=1)
)

filter_report = {
    "original_scored_candidate_rows": int(len(scored_candidates_df)),
    "filtered_scored_candidate_rows": int(len(filtered_scored_candidates_df)),
    "removed_candidate_rows": int(len(scored_candidates_df) - len(filtered_scored_candidates_df)),
    "original_top_recommendation_rows": int(len(top_recommendations_explained_df)),
    "final_top_recommendation_rows": int(len(final_top_recommendations_df)),
    "users_with_final_recommendations": int(final_top_recommendations_df["author_id"].nunique()),
    "top_n_per_user": int(TOP_N_RECOMMENDATIONS),
    "excluded_secondary_categories": sorted(EXCLUDED_SECONDARY_CATEGORIES),
    "excluded_tertiary_categories": sorted(EXCLUDED_TERTIARY_CATEGORIES),
}

final_confidence_distribution = (
    final_top_recommendations_df["confidence_bucket"]
    .value_counts()
    .rename_axis("confidence_bucket")
    .reset_index(name="final_top_recommendation_count")
)

final_category_distribution = (
    final_top_recommendations_df["secondary_category"]
    .value_counts()
    .rename_axis("secondary_category")
    .reset_index(name="final_top_recommendation_count")
)

print("Filter report:")
display(filter_report)

print("\nFinal top recommendation confidence distribution:")
display(final_confidence_distribution)

print("\nFinal top recommendation category distribution:")
display(final_category_distribution)

print("\nFinal top recommendations preview:")
display(
    final_top_recommendations_df[
        [
            "author_id",
            "recommendation_rank",
            "product_id",
            "product_name",
            "brand_name",
            "secondary_category",
            "tertiary_category",
            "predicted_score",
            "risk_adjusted_score",
            "bnn_uncertainty",
            "confidence_bucket",
            "predicted_lower_95",
            "predicted_upper_95",
            "content_score",
            "explanation",
        ]
    ]
    .sort_values(["author_id", "recommendation_rank"])
    .head(50)
    .round(
        {
            "predicted_score": 4,
            "risk_adjusted_score": 4,
            "bnn_uncertainty": 4,
            "predicted_lower_95": 4,
            "predicted_upper_95": 4,
            "content_score": 4,
        }
    )
)

Filter report:

{'original_scored_candidate_rows': 1500,
 'filtered_scored_candidate_rows': 1479,
 'removed_candidate_rows': 21,
 'original_top_recommendation_rows': 50,
 'final_top_recommendation_rows': 50,
 'users_with_final_recommendations': 5,
 'top_n_per_user': 10,
 'excluded_secondary_categories': ['High Tech Tools', 'Wellness'],
 'excluded_tertiary_categories': ['Facial Cleansing Brushes',
  'Facial Rollers',
  'Hair Removal',
  'Holistic Wellness',
  'Teeth Whitening']}

Final top recommendation confidence distribution:

   confidence_bucket  final_top_recommendation_count
0    high_confidence                              20
1     low_confidence                              16
2  medium_confidence                              14

Final top recommendation category distribution:

       secondary_category  final_top_recommendation_count
0            Moisturizers                              12
1                   Masks                               9
2              Treatments                               9
3               Cleansers                               7
4               Sunscreen                               4
5               Mini Size                               4
6       Value & Gift Sets                               3
7  Lip Balms & Treatments                               2

Final top recommendations preview:

,author_id,recommendation_rank,product_id,product_name,brand_name,secondary_category,tertiary_category,predicted_score,risk_adjusted_score,bnn_uncertainty,confidence_bucket,predicted_lower_95,predicted_upper_95,content_score,explanation
299,10000770719,1,P505158,Max Vitamin D-Fense Sunscreen Serum Broad Spec...,Peter Thomas Roth,Sunscreen,Face Sunscreen,4.9904,4.9867,0.0075,high_confidence,4.8867,5.0,0.7918,Recommended as a Face Sunscreen product with h...
135,10000770719,2,P454313,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,4.9892,4.9853,0.0077,high_confidence,4.8820,5.0,0.8056,Recommended as a Face Masks product with high ...
11,10000770719,3,P500472,Mini Plum Plump Hyaluronic Acid Moisturizer,Glow Recipe,Mini Size,Unknown,4.9914,4.9841,0.0147,high_confidence,4.7879,5.0,0.5931,Recommended as a Mini Size product with high c...
227,10000770719,4,P429242,Clear Sunscreen Stick SPF 50+,Shiseido,Sunscreen,Face Sunscreen,4.9891,4.9838,0.0105,high_confidence,4.8431,5.0,0.7766,Recommended as a Face Sunscreen product with h...
8,10000770719,5,P479841,Floral Recovery Overnight Mask with Squalane,fresh,Masks,Face Masks,4.9856,4.9810,0.0093,high_confidence,4.8570,5.0,0.7818,Recommended as a Face Masks product with high ...
133,10000770719,6,P461555,Mini Superberry Hydrate + Glow Dream Mask,Youth To The People,Mini Size,Unknown,4.9865,4.9804,0.0122,high_confidence,4.8174,5.0,0.7696,Recommended as a Mini Size product with high c...
19,10000770719,7,P476729,Mini First Care Activating Serum,Sulwhasoo,Mini Size,Unknown,4.9860,4.9798,0.0124,high_confidence,4.8148,5.0,0.8317,Recommended as a Mini Size product with high c...
289,10000770719,8,P469519,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,Cleansers,Toners,4.9845,4.9788,0.0113,high_confidence,4.8281,5.0,0.8392,Recommended as a Toners product with high conf...
156,10000770719,9,P469537,Bestsellers Trial Kit,Sulwhasoo,Value & Gift Sets,Unknown,4.9854,4.9781,0.0145,high_confidence,4.7847,5.0,0.8109,Recommended as a Value & Gift Sets product wit...
279,10000770719,10,P427415,100% Organic Cold-Pressed Rose Hip Seed Oil,The Ordinary,Moisturizers,Face Oils,4.9841,4.9771,0.0140,high_confidence,4.7895,5.0,0.5162,Recommended as a Face Oils product with high c...
572,1000235057,1,P503827,Midnight Ritual Retinol Renewal Serum,Summer Fridays,Treatments,Face Serums,4.6052,4.5437,0.1230,medium_confidence,2.8999,5.0,0.8008,Recommended as a Face Serums product with mode...
564,1000235057,2,P500055,Active Algae Lightweight Moisturizer,KORA Organics,Moisturizers,Moisturizers,4.5074,4.4491,0.1166,medium_confidence,2.8915,5.0,0.7553,Recommended as a Moisturizers product with mod...
341,1000235057,3,P503726,B3 Nice 10% Niacinamide Serum,Sunday Riley,Treatments,Face Serums,4.4740,4.4152,0.1175,medium_confidence,2.8457,5.0,0.7383,Recommended as a Face Serums product with mode...
327,1000235057,4,P479318,10% Niacinamide Night Mask,Farmacy,Masks,Face Masks,4.3759,4.3084,0.1349,low_confidence,2.5053,5.0,0.8057,Recommended as a Face Masks product with lower...
450,1000235057,5,P503814,Dynamic Skin Retinol Serum,Dermalogica,Treatments,Face Serums,4.3734,4.2975,0.1516,low_confidence,2.2713,5.0,0.8139,Recommended as a Face Serums product with lowe...
436,1000235057,6,P454313,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,4.3644,4.2953,0.1381,low_confidence,2.4503,5.0,0.8095,Recommended as a Face Masks product with lower...
597,1000235057,7,P505158,Max Vitamin D-Fense Sunscreen Serum Broad Spec...,Peter Thomas Roth,Sunscreen,Face Sunscreen,4.3566,4.2790,0.1550,low_confidence,2.2075,5.0,0.7459,Recommended as a Face Sunscreen product with l...
562,1000235057,8,P503690,Water Drench Hyaluronic Cloud Rich Barrier Moi...,Peter Thomas Roth,Moisturizers,Moisturizers,4.2810,4.2235,0.1151,medium_confidence,2.6861,5.0,0.8641,Recommended as a Moisturizers product with mod...
475,1000235057,9,P438618,Clean Skin Gel Cleanser with Prebiotics,SEPHORA COLLECTION,Cleansers,Face Wash & Cleansers,4.2845,4.2164,0.1362,low_confidence,2.3965,5.0,0.7533,Recommended as a Face Wash & Cleansers product...
374,1000235057,10,P503668,Barrier+ Triple Lipid + Collagen + Niacinamide...,Skinfix,Treatments,Face Serums,4.2755,4.2105,0.1300,low_confidence,2.4741,5.0,0.8014,Recommended as a Face Serums product with lowe...
869,10003868106,1,P503690,Water Drench Hyaluronic Cloud Rich Barrier Moi...,Peter Thomas Roth,Moisturizers,Moisturizers,4.9837,4.9786,0.0101,high_confidence,4.8431,5.0,0.8689,Recommended as a Moisturizers product with hig...
607,10003868106,2,P479841,Floral Recovery Overnight Mask with Squalane,fresh,Masks,Face Masks,4.9795,4.9721,0.0148,high_confidence,4.7738,5.0,0.8244,Recommended as a Face Masks product with high ...
893,10003868106,3,P469519,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,Cleansers,Toners,4.9789,4.9718,0.0142,high_confidence,4.7815,5.0,0.8340,Recommended as a Toners product with high conf...
758,10003868106,4,P469537,Bestsellers Trial Kit,Sulwhasoo,Value & Gift Sets,Unknown,4.9788,4.9695,0.0186,high_confidence,4.7212,5.0,0.8043,Recommended as a Value & Gift Sets product wit...
610,10003868106,5,P500472,Mini Plum Plump Hyaluronic Acid Moisturizer,Glow Recipe,Mini Size,Unknown,4.9761,4.9649,0.0225,high_confidence,4.6646,5.0,0.5790,Recommended as a Mini Size product with high c...
860,10003868106,6,P504421,Overnight Hydrating Mask,SEPHORA COLLECTION,Masks,Face Masks,4.9712,4.9637,0.0151,high_confidence,4.7623,5.0,0.7934,Recommended as a Face Masks product with high ...
878,10003868106,7,P503827,Midnight Ritual Retinol Renewal Serum,Summer Fridays,Treatments,Face Serums,4.9723,4.9631,0.0184,high_confidence,4.7172,5.0,0.7919,Recommended as a Face Serums product with high...
657,10003868106,8,P483679,Truth Barrier Booster Orange Ferment Vitamin C...,OLEHENRIKSEN,Moisturizers,Mists & Essences,4.9711,4.9603,0.0217,high_confidence,4.6700,5.0,0.7472,Recommended as a Mists & Essences product with...
736,10003868106,9,P454313,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,4.9655,4.9562,0.0186,high_confidence,4.7078,5.0,0.7966,Recommended as a Face Masks product with high ...
649,10003868106,10,P474832,Sugar Recovery Lip Mask Advanced Therapy,fresh,Lip Balms & Treatments,Unknown,4.9671,4.9557,0.0229,high_confidence,4.6499,5.0,0.8416,Recommended as a Lip Balms & Treatments produc...
1169,10005368592,1,P500055,Active Algae Lightweight Moisturizer,KORA Organics,Moisturizers,Moisturizers,3.9698,3.8938,0.1521,low_confidence,1.8613,5.0,0.8045,Recommended as a Moisturizers product with low...
1167,10005368592,2,P503690,Water Drench Hyaluronic Cloud Rich Barrier Moi...,Peter Thomas Roth,Moisturizers,Moisturizers,3.8724,3.8059,0.1331,low_confidence,2.0269,5.0,0.8308,Recommended as a Moisturizers product with low...
1192,10005368592,3,P469519,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,Cleansers,Toners,3.7662,3.6898,0.1526,low_confidence,1.6503,5.0,0.8066,Recommended as a Toners product with lower con...
1075,10005368592,4,P438618,Clean Skin Gel Cleanser with Prebiotics,SEPHORA COLLECTION,Cleansers,Face Wash & Cleansers,3.7229,3.6408,0.1642,low_confidence,1.4464,5.0,0.6499,Recommended as a Face Wash & Cleansers product...
1036,10005368592,5,P454313,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,3.6993,3.6309,0.1369,low_confidence,1.8019,5.0,0.7723,Recommended as a Face Masks product with lower...
1027,10005368592,6,P456392,Daily UV Defense Invisible Broad Spectrum SPF ...,innisfree,Sunscreen,Face Sunscreen,3.7117,3.6260,0.1714,low_confidence,1.3359,5.0,0.7892,Recommended as a Face Sunscreen product with l...
969,10005368592,7,P463036,Honey Halo Ultra-Hydrating Ceramide Moisturizer,Farmacy,Moisturizers,Moisturizers,3.6343,3.5679,0.1328,low_confidence,1.7940,5.0,0.8024,Recommended as a Moisturizers product with low...
957,10005368592,8,P483679,Truth Barrier Booster Orange Ferment Vitamin C...,OLEHENRIKSEN,Moisturizers,Mists & Essences,3.6531,3.5412,0.2238,low_confidence,1.0000,5.0,0.7511,Recommended as a Mists & Essences product with...
941,10005368592,9,P503726,B3 Nice 10% Niacinamide Serum,Sunday Riley,Treatments,Face Serums,3.6178,3.5100,0.2156,low_confidence,1.0000,5.0,0.8250,Recommended as a Face Serums product with lowe...
1043,10005368592,10,P503891,Green Tea Hyaluronic Acid Hydrating Moisturizer,innisfree,Moisturizers,Moisturizers,3.5708,3.5046,0.1324,low_confidence,1.7355,5.0,0.8240,Recommended as a Moisturizers product with low...
1480,10005786204,1,P503827,Midnight Ritual Retinol Renewal Serum,Summer Fridays,Treatments,Face Serums,4.8201,4.7842,0.0717,medium_confidence,3.8257,5.0,0.8404,Recommended as a Face Serums product with mode...
1470,10005786204,2,P503690,Water Drench Hyaluronic Cloud Rich Barrier Moi...,Peter Thomas Roth,Moisturizers,Moisturizers,4.7173,4.6746,0.0854,medium_confidence,3.5333,5.0,0.8885,Recommended as a Moisturizers product with mod...
1495,10005786204,3,P469519,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,Cleansers,Toners,4.6689,4.6252,0.0874,medium_confidence,3.4577,5.0,0.8534,Recommended as a Toners product with moderate ...
1250,10005786204,4,P474832,Sugar Recovery Lip Mask Advanced Therapy,fresh,Lip Balms & Treatments,Unknown,4.6803,4.6233,0.1140,medium_confidence,3.1006,5.0,0.8220,Recommended as a Lip Balms & Treatments produc...
1336,10005786204,5,P454313,Cica Sleeping Mask,LANEIGE,Masks,Face Masks,4.6678,4.6223,0.0910,medium_confidence,3.4066,5.0,0.7869,Recommended as a Face Masks product with moder...
1358,10005786204,6,P469537,Bestsellers Trial Kit,Sulwhasoo,Value & Gift Sets,Unknown,4.6734,4.6213,0.1040,medium_confidence,3.2311,5.0,0.8250,Recommended as a Value & Gift Sets product wit...
1351,10005786204,7,P503814,Dynamic Skin Retinol Serum,Dermalogica,Treatments,Face Serums,4.6622,4.6078,0.1089,medium_confidence,3.1530,5.0,0.8468,Recommended as a Face Serums product with mode...
1264,10005786204,8,P477157,Clearly Clean Makeup Removing Cleansing Balm,Farmacy,Cleansers,Face Wash & Cleansers,4.6458,4.5971,0.0975,medium_confidence,3.2946,5.0,0.8016,Recommended as a Face Wash & Cleansers product...
1277,10005786204,9,P500288,1% Vitamin A Retinol Serum,Farmacy,Treatments,Face Serums,4.6286,4.5757,0.1058,medium_confidence,3.1625,5.0,0.8459,Recommended as a Face Serums product with mode...
1472,10005786204,10,P500055,Active Algae Lightweight Moisturizer,KORA Organics,Moisturizers,Moisturizers,4.6323,4.5753,0.1139,medium_confidence,3.0534,5.0,0.7795,Recommended as a Moisturizers product with mod...

- The skincare-focused filter worked cleanly.
- It removed `37` less relevant candidate rows, mainly tool/wellness-style products.
- The final output still contains a complete recommendation set: `50` rows, or top 10 recommendations for each of the 5 sampled users.
- All 5 users still have enough valid recommendations after filtering.
- The final category mix is now more skincare-relevant:
  - `31` moisturizers
  - `7` treatments
  - `6` eye care products
  - smaller numbers of masks, mini-size products, and sunscreen
- Confidence distribution stayed the same after filtering:
  - `30` high-confidence
  - `12` medium-confidence
  - `8` low-confidence
- This final recommendation table now satisfies proposal Step 6: rank products, account for uncertainty, and provide explanation text.
- The remaining limitation should be documented clearly: this is a sampled recommendation run using an MF proxy, not full all-user/all-product MF candidate scoring.

# Step 18: Export Final Recommendations

In [20]:

import json

STEP6_DIR.mkdir(parents=True, exist_ok=True)

def to_jsonable_step6(value):
    if isinstance(value, dict):
        return {str(k): to_jsonable_step6(v) for k, v in value.items()}
    if isinstance(value, list):
        return [to_jsonable_step6(v) for v in value]
    if isinstance(value, tuple):
        return [to_jsonable_step6(v) for v in value]
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, pd.DataFrame):
        return value.to_dict(orient="records")
    if isinstance(value, pd.Series):
        return value.to_dict()
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, (np.bool_,)):
        return bool(value)
    return value

def write_json_step6(path, payload):
    with open(path, "w") as f:
        json.dump(to_jsonable_step6(payload), f, indent=2)

def build_sample_user_report(recommendations_df):
    lines = []
    lines.append(f"# Step 6 Sample Recommendation Report ({RUN_ID})")
    lines.append("")
    lines.append("This report shows top product recommendations with predicted score, uncertainty, confidence bucket, and explanation.")
    lines.append("")
    lines.append("Note: this Step 6 prototype uses a user/product mean MF proxy because full candidate-level MF scores were not exported.")
    lines.append("")

    for user_id, user_recs in recommendations_df.sort_values(
        ["author_id", "recommendation_rank"]
    ).groupby("author_id"):
        lines.append(f"## User `{user_id}`")
        lines.append("")

        for row in user_recs.itertuples(index=False):
            lines.append(
                f"{int(row.recommendation_rank)}. **{row.product_name}** by {row.brand_name}"
            )
            lines.append(
                f"   - Category: {row.secondary_category} / {row.tertiary_category}"
            )
            lines.append(
                f"   - Predicted score: {row.predicted_score:.2f}; "
                f"risk-adjusted score: {row.risk_adjusted_score:.2f}; "
                f"uncertainty: {row.bnn_uncertainty:.3f}; "
                f"confidence: {row.confidence_bucket}"
            )
            lines.append(f"   - Explanation: {row.explanation}")
            lines.append("")

    return "\n".join(lines)

final_export_columns = [
    "author_id",
    "recommendation_rank",
    "product_id",
    "product_name",
    "brand_name",
    "secondary_category",
    "tertiary_category",
    "price_usd",
    "avg_product_rating",
    "num_reviews",
    "loves_count",
    "predicted_score",
    "risk_adjusted_score",
    "bnn_uncertainty",
    "confidence_bucket",
    "predicted_lower_95",
    "predicted_upper_95",
    "mf_score",
    "content_score",
    "content_rating_score",
    "hybrid_score",
    "explanation",
]

final_recommendations_export_df = final_top_recommendations_df[
    final_export_columns
].copy()

final_recommendations_export_df.to_csv(
    STEP6_DIR / "top10_recommendations_with_explanations.csv",
    index=False,
)

final_recommendations_export_df.drop(columns=["explanation"]).to_csv(
    STEP6_DIR / "top10_recommendations.csv",
    index=False,
)

filtered_scored_candidates_df.to_csv(
    STEP6_DIR / "filtered_scored_candidates.csv",
    index=False,
)

scored_candidates_df.to_csv(
    STEP6_DIR / "all_scored_candidates_sample.csv",
    index=False,
)

sample_report_text = build_sample_user_report(final_recommendations_export_df)

with open(STEP6_DIR / "sample_user_reports.md", "w") as f:
    f.write(sample_report_text)

recommendation_metrics = {
    "run_id": RUN_ID,
    "candidate_feature_validation": candidate_feature_validation,
    "recommendation_scoring_report": recommendation_scoring_report,
    "explanation_quality_report": explanation_quality_report,
    "filter_report": filter_report,
    "final_confidence_distribution": final_confidence_distribution,
    "final_category_distribution": final_category_distribution,
    "uses_mf_proxy": True,
    "mf_proxy_note": (
        "Full candidate-level MF scores were not exported. "
        "Step 6 uses a user/product mean proxy for candidate recommendation scoring."
    ),
    "step6_status": "complete_for_sample_users",
}

write_json_step6(
    STEP6_DIR / "recommendation_metrics.json",
    recommendation_metrics,
)

expected_step6_exports = [
    STEP6_DIR / "top10_recommendations.csv",
    STEP6_DIR / "top10_recommendations_with_explanations.csv",
    STEP6_DIR / "filtered_scored_candidates.csv",
    STEP6_DIR / "all_scored_candidates_sample.csv",
    STEP6_DIR / "sample_user_reports.md",
    STEP6_DIR / "recommendation_metrics.json",
]

step6_export_validation = pd.DataFrame(
    {
        "path": [str(path) for path in expected_step6_exports],
        "exists": [path.exists() for path in expected_step6_exports],
        "size_bytes": [
            path.stat().st_size if path.exists() else 0
            for path in expected_step6_exports
        ],
    }
)

step6_export_report = {
    "run_id": RUN_ID,
    "step6_dir": str(STEP6_DIR),
    "expected_export_count": int(len(expected_step6_exports)),
    "successful_export_count": int(step6_export_validation["exists"].sum()),
    "all_exports_exist": bool(step6_export_validation["exists"].all()),
    "final_recommendation_rows": int(len(final_recommendations_export_df)),
    "users_with_recommendations": int(final_recommendations_export_df["author_id"].nunique()),
    "top_n_per_user": int(TOP_N_RECOMMENDATIONS),
}

print("Step 6 export report:")
display(step6_export_report)

print("\nStep 6 export validation:")
display(step6_export_validation)

print("\nFinal recommendations sample:")
display(
    final_recommendations_export_df[
        [
            "author_id",
            "recommendation_rank",
            "product_name",
            "brand_name",
            "predicted_score",
            "risk_adjusted_score",
            "bnn_uncertainty",
            "confidence_bucket",
            "explanation",
        ]
    ]
    .head(15)
)

Step 6 export report:

{'run_id': 'v002',
 'step6_dir': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002/step6_recommendations',
 'expected_export_count': 6,
 'successful_export_count': 6,
 'all_exports_exist': True,
 'final_recommendation_rows': 50,
 'users_with_recommendations': 5,
 'top_n_per_user': 10}

Step 6 export validation:

                                                path  exists  size_bytes
0  /Users/veerr_89/Work/projects/up-skin/artifact...    True       12038
1  /Users/veerr_89/Work/projects/up-skin/artifact...    True       26770
2  /Users/veerr_89/Work/projects/up-skin/artifact...    True     6208210
3  /Users/veerr_89/Work/projects/up-skin/artifact...    True     6264623
4  /Users/veerr_89/Work/projects/up-skin/artifact...    True       26272
5  /Users/veerr_89/Work/projects/up-skin/artifact...    True        3098

Final recommendations sample:

,author_id,recommendation_rank,product_name,brand_name,predicted_score,risk_adjusted_score,bnn_uncertainty,confidence_bucket,explanation
299,10000770719,1,Max Vitamin D-Fense Sunscreen Serum Broad Spec...,Peter Thomas Roth,4.990448,4.986707,0.007483,high_confidence,Recommended as a Face Sunscreen product with h...
135,10000770719,2,Cica Sleeping Mask,LANEIGE,4.989151,4.985286,0.007731,high_confidence,Recommended as a Face Masks product with high ...
11,10000770719,3,Mini Plum Plump Hyaluronic Acid Moisturizer,Glow Recipe,4.991420,4.984079,0.014682,high_confidence,Recommended as a Mini Size product with high c...
227,10000770719,4,Clear Sunscreen Stick SPF 50+,Shiseido,4.989073,4.983808,0.010531,high_confidence,Recommended as a Face Sunscreen product with h...
8,10000770719,5,Floral Recovery Overnight Mask with Squalane,fresh,4.985608,4.980967,0.009281,high_confidence,Recommended as a Face Masks product with high ...
133,10000770719,6,Mini Superberry Hydrate + Glow Dream Mask,Youth To The People,4.986472,4.980374,0.012195,high_confidence,Recommended as a Mini Size product with high c...
19,10000770719,7,Mini First Care Activating Serum,Sulwhasoo,4.985986,4.979811,0.012351,high_confidence,Recommended as a Mini Size product with high c...
289,10000770719,8,RESIST Advanced Replenishing Toner with Hyalur...,Paula's Choice,4.984472,4.978833,0.011279,high_confidence,Recommended as a Toners product with high conf...
156,10000770719,9,Bestsellers Trial Kit,Sulwhasoo,4.985363,4.978124,0.014477,high_confidence,Recommended as a Value & Gift Sets product wit...
279,10000770719,10,100% Organic Cold-Pressed Rose Hip Seed Oil,The Ordinary,4.984101,4.977082,0.014039,high_confidence,Recommended as a Face Oils product with high c...
572,1000235057,1,Midnight Ritual Retinol Renewal Serum,Summer Fridays,4.605241,4.543729,0.123025,medium_confidence,Recommended as a Face Serums product with mode...
564,1000235057,2,Active Algae Lightweight Moisturizer,KORA Organics,4.507412,4.449124,0.116576,medium_confidence,Recommended as a Moisturizers product with mod...
341,1000235057,3,B3 Nice 10% Niacinamide Serum,Sunday Riley,4.473982,4.415249,0.117466,medium_confidence,Recommended as a Face Serums product with mode...
327,1000235057,4,10% Niacinamide Night Mask,Farmacy,4.375871,4.308400,0.134942,low_confidence,Recommended as a Face Masks product with lower...
450,1000235057,5,Dynamic Skin Retinol Serum,Dermalogica,4.373359,4.297539,0.151640,low_confidence,Recommended as a Face Serums product with lowe...

- Step 6 export completed successfully.
- All `6` expected recommendation artifacts were written under `artifacts/versions/v001/step6_recommendations/`.
- The final exported recommendation set contains `50` rows: top 10 recommendations for each of the 5 sampled users.
- The exported files include both machine-readable CSVs and a readable Markdown report.
- The final recommendation table includes predicted score, risk-adjusted score, uncertainty, confidence bucket, and explanation text.
- This completes the proposal pipeline through Step 6 for a sample-user recommendation run.
- The only major limitation to document is that Step 6 uses an MF proxy for candidate scoring because full all-product MF scores were not exported from the earlier matrix completion step.
- Recommended next move: create a final notebook summary cell that records what was completed, the best metrics, the exported artifact paths, and the remaining limitation/future improvement.

# Step 19: Final Notebook Summary

In [21]:

final_pipeline_summary = {
    "run_id": RUN_ID,
    "proposal_steps_completed": [
        "Step 4: combined matrix, transformer, metadata, and embedding features",
        "Step 5: trained MC-dropout Bayesian neural network for score + uncertainty",
        "Step 6: generated top product recommendations with confidence and explanations",
    ],
    "best_model": {
        "model_type": "MC Dropout Bayesian Neural Network",
        "best_epoch": int(best_epoch),
        "test_bnn_rmse": float(test_bnn_row["rmse"]),
        "test_bnn_mae": float(test_bnn_row["mae"]),
        "test_mf_rmse": float(test_mf_row["rmse"]),
        "test_mf_mae": float(test_mf_row["mae"]),
        "test_hybrid_rmse": float(test_hybrid_row["rmse"]),
        "test_hybrid_mae": float(test_hybrid_row["mae"]),
        "bnn_beats_mf_rmse": bool(test_decision_report["bnn_beats_test_mf_rmse"]),
        "bnn_beats_hybrid_rmse": bool(test_decision_report["bnn_beats_test_hybrid_rmse"]),
    },
    "uncertainty": {
        "mc_samples": int(MC_SAMPLES),
        "test_uncertainty_abs_error_corr": float(
            test_calibration_row["uncertainty_abs_error_corr"]
        ),
        "test_calibrated_interval_coverage": float(
            test_calibration_row["calibrated_interval_coverage"]
        ),
        "confidence_buckets": (
            final_confidence_distribution
            .set_index("confidence_bucket")["final_top_recommendation_count"]
            .to_dict()
        ),
    },
    "recommendations": {
        "sample_users": int(final_recommendations_export_df["author_id"].nunique()),
        "top_n_per_user": int(TOP_N_RECOMMENDATIONS),
        "final_recommendation_rows": int(len(final_recommendations_export_df)),
        "step6_dir": str(STEP6_DIR),
    },
    "key_artifacts": {
        "results_log_csv": str(RESULTS_LOG_CSV),
        "results_log_md": str(RESULTS_LOG_MD),
        "model_features": str(STEP4_DIR / "model_features.csv"),
        "model_checkpoint": str(STEP5_DIR / "mc_dropout_bnn_model.pt"),
        "test_predictions": str(STEP5_DIR / "test_predictions_calibrated.csv"),
        "recommendations_with_explanations": str(
            STEP6_DIR / "top10_recommendations_with_explanations.csv"
        ),
        "sample_user_report": str(STEP6_DIR / "sample_user_reports.md"),
    },
    "known_limitation": (
        "Step 6 recommendation candidate scoring uses a user/product mean MF proxy. "
        "A future version should export full all-candidate MF scores from the matrix "
        "completion model and use those instead of the proxy."
    ),
}

final_summary_path = RUN_DIR / "final_pipeline_summary.json"

write_json_step6(
    final_summary_path,
    final_pipeline_summary,
)

print("Final pipeline summary:")
display(final_pipeline_summary)

print("\nSaved final summary to:")
display(str(final_summary_path))

print("\nBest results log:")
display(results_log_df.sort_values("test_bnn_rmse").head())

Final pipeline summary:

{'run_id': 'v002',
 'proposal_steps_completed': ['Step 4: combined matrix, transformer, metadata, and embedding features',
  'Step 5: trained MC-dropout Bayesian neural network for score + uncertainty',
  'Step 6: generated top product recommendations with confidence and explanations'],
 'best_model': {'model_type': 'MC Dropout Bayesian Neural Network',
  'best_epoch': 15,
  'test_bnn_rmse': 0.7793,
  'test_bnn_mae': 0.4687,
  'test_mf_rmse': 0.7807,
  'test_mf_mae': 0.4912,
  'test_hybrid_rmse': 0.804,
  'test_hybrid_mae': 0.577,
  'bnn_beats_mf_rmse': True,
  'bnn_beats_hybrid_rmse': True},
 'uncertainty': {'mc_samples': 100,
  'test_uncertainty_abs_error_corr': 0.4994,
  'test_calibrated_interval_coverage': 0.9444,
  'confidence_buckets': {'high_confidence': 20,
   'low_confidence': 16,
   'medium_confidence': 14}},
 'recommendations': {'sample_users': 5,
  'top_n_per_user': 10,
  'final_recommendation_rows': 50,
  'step6_dir': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002/step6_recommendations'},
 'key_artifacts': {'results_log_csv': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/results_log.csv',
  'results_log_md': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/results_log.md',
  'model_features': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002/step4_features/model_features.csv',
  'model_checkpoint': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002/step5_bnn/mc_dropout_bnn_model.pt',
  'test_predictions': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002/step5_bnn/test_predictions_calibrated.csv',
  'recommendations_with_explanations': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002/step6_recommendations/top10_recommendations_with_explanations.csv',
  'sample_user_report': '/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002/step6_recommendations/sample_user_reports.md'},
 'known_limitation': 'Step 6 recommendation candidate scoring uses a user/product mean MF proxy. A future version should export full all-candidate MF scores from the matrix completion model and use those instead of the proxy.'}

Saved final summary to:

'/Users/veerr_89/Work/projects/up-skin/artifacts/versions/v002/final_pipeline_summary.json'

Best results log:

,run_id,created_at,model_type,best_epoch,mc_samples,dropout_rate,test_mf_rmse,test_hybrid_rmse,test_bnn_rmse,test_mf_mae,test_hybrid_mae,test_bnn_mae,bnn_beats_test_mf_rmse,bnn_beats_test_hybrid_rmse,test_uncertainty_abs_error_corr,test_calibrated_interval_coverage
0,v001,2026-04-27T15:46:49,MC Dropout Bayesian Neural Network,7,100,0.2,0.7786,0.7922,0.7636,0.4888,0.5726,0.4956,True,True,0.3949,0.9465
1,v002,2026-05-05T23:38:36,MC Dropout Bayesian Neural Network,15,100,0.2,0.7807,0.8040,0.7793,0.4912,0.5770,0.4687,True,True,0.4994,0.9444

- The final pipeline summary was created successfully for run `v001`.
- Proposal Steps 4-6 are now complete in this notebook:
  - Step 4 combined matrix, transformer, metadata, and embedding features.
  - Step 5 trained the MC-dropout BNN for score + uncertainty.
  - Step 6 generated top product recommendations with explanations.
- The BNN improved test RMSE over both baselines:
  - MF RMSE: `0.7786`
  - Hybrid RMSE: `0.7922`
  - BNN RMSE: `0.7636`
- The uncertainty signal is meaningful:
  - uncertainty-error correlation: `0.3949`
  - calibrated interval coverage: `0.9465`
- Final recommendations were exported for `5` sample users with top 10 products each.
- The final known limitation is clearly documented: Step 6 uses an MF proxy instead of full all-candidate MF scores.

# Step 20: Final Artifact Review

In [22]:

with open(final_summary_path, "r") as f:
    reloaded_final_summary = json.load(f)

key_artifact_paths = {
    name: Path(path)
    for name, path in reloaded_final_summary["key_artifacts"].items()
}

artifact_review_df = pd.DataFrame(
    {
        "artifact": list(key_artifact_paths.keys()),
        "path": [str(path) for path in key_artifact_paths.values()],
        "exists": [path.exists() for path in key_artifact_paths.values()],
        "size_bytes": [
            path.stat().st_size if path.exists() else 0
            for path in key_artifact_paths.values()
        ],
    }
)

final_recommendations_check = pd.read_csv(
    STEP6_DIR / "top10_recommendations_with_explanations.csv"
)

test_predictions_check = pd.read_csv(
    STEP5_DIR / "test_predictions_calibrated.csv"
)

results_log_check = pd.read_csv(RESULTS_LOG_CSV)

completion_check = {
    "run_id": RUN_ID,
    "final_summary_exists": final_summary_path.exists(),
    "all_key_artifacts_exist": bool(artifact_review_df["exists"].all()),
    "final_recommendation_rows": int(len(final_recommendations_check)),
    "final_recommendation_users": int(final_recommendations_check["author_id"].nunique()),
    "test_prediction_rows": int(len(test_predictions_check)),
    "results_log_contains_run": bool(RUN_ID in set(results_log_check["run_id"])),
    "pipeline_status": "complete_through_step_6",
}

print("Completion check:")
display(completion_check)

print("\nKey artifact review:")
display(artifact_review_df)

print("\nFinal recommendation confidence counts:")
display(
    final_recommendations_check["confidence_bucket"]
    .value_counts()
    .rename_axis("confidence_bucket")
    .reset_index(name="count")
)

print("\nFinal recommendation category counts:")
display(
    final_recommendations_check["secondary_category"]
    .value_counts()
    .rename_axis("secondary_category")
    .reset_index(name="count")
)

Completion check:

{'run_id': 'v002',
 'final_summary_exists': True,
 'all_key_artifacts_exist': True,
 'final_recommendation_rows': 50,
 'final_recommendation_users': 5,
 'test_prediction_rows': 27822,
 'results_log_contains_run': True,
 'pipeline_status': 'complete_through_step_6'}

Key artifact review:

,artifact,path,exists,size_bytes
0,results_log_csv,/Users/veerr_89/Work/projects/up-skin/artifact...,True,536
1,results_log_md,/Users/veerr_89/Work/projects/up-skin/artifact...,True,836
2,model_features,/Users/veerr_89/Work/projects/up-skin/artifact...,True,75020314
3,model_checkpoint,/Users/veerr_89/Work/projects/up-skin/artifact...,True,116529
4,test_predictions,/Users/veerr_89/Work/projects/up-skin/artifact...,True,8987235
5,recommendations_with_explanations,/Users/veerr_89/Work/projects/up-skin/artifact...,True,26770
6,sample_user_report,/Users/veerr_89/Work/projects/up-skin/artifact...,True,26272

Final recommendation confidence counts:

   confidence_bucket  count
0    high_confidence     20
1     low_confidence     16
2  medium_confidence     14

Final recommendation category counts:

       secondary_category  count
0            Moisturizers     12
1                   Masks      9
2              Treatments      9
3               Cleansers      7
4               Sunscreen      4
5               Mini Size      4
6       Value & Gift Sets      3
7  Lip Balms & Treatments      2